### ISSUE TITLE
[FEATURE] Be able to lock the version of python open-api-gateway api project

### ISSUE THREAD

**Issue by jessieweiyi** [aws/aws-pdk#164]
### Describe the feature

Currently, there is no way to lock the version of python *@aws-prototyping-sdk/open-api-gateway* deps in the API project itself since the project is automatically generated. 

Even when the version of *@aws-prototyping-sdk/open-api-gateway* is locked in the monorepo definition, the version in the API project is not locked. 

When there is any breaking change in the lib, the CI/CD pipeline will break since it is always installing the latest version if we cannot lock the version from requirements.txt or use tooling like pipenv. 

### Use Case

Now when there is any breaking change in the lib, the CI/CD pipeline will break since it is always installing the latest version if we cannot lock the version from requirements.txt or use tooling like pipenv. 

### Proposed Solution

The *@aws-prototyping-sdk/open-api-gateway* should have the same version as the monorepo project if it is locked so that we have consistent build result. 

### Other Information

This is when I tried to lock the version: 

projen.rc file
```
const monorepo = new nx_monorepo.NxMonorepoProject({
  defaultReleaseBranch: 'mainline',
  devDeps: ['aws-prototyping-sdk@0.10.2'],
  deps: [
    '@aws-prototyping-sdk/cloudscape-react-ts-website@0.10.2', 
    '@aws-prototyping-sdk/open-api-gateway@0.10.2'
  ],
  gitignore: [".env", ".ipynb_checkpoints"],
  name: '******',
  tsconfig: {
    compilerOptions: {},
    include: [
      "packages/**/*.ts",
      "packages/**/*.tsx",
    ]
  }
});
```

deps.json file of the monorepo 
```
```
    {
      "name": "@aws-prototyping-sdk/open-api-gateway",
      "version": "0.10.2",
      "type": "runtime"
    },
```

deps.json file of the api project
```
    {
      "name": "aws_prototyping_sdk.open_api_gateway",
      "type": "runtime"
    },
```



### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PDK version used

0.11.0

### What languages will this feature affect?

Python

### Environment details (OS name and version, etc.)

CodePipeline

**Comment by cogwirrel** [comment]
Thanks for raising this! We should definitely let you pin the version of open-api-gateway in the api project!

Given that this project is designed to be used either within a monorepo or as a standalone project, perhaps we instead allow the version to be specified in `deps` for the api project itself rather than looking for the version in the monorepo? This would mean adding the following to your `.projenrc`:

```ts
new OpenApiGatewayPythonProject({
  ...,
  deps: ["aws_prototyping_sdk.open_api_gateway@0.10.2"], // <- pin the version to 0.10.2
});
```

We should also have the same behaviour for Java and TypeScript :)
