### ISSUE TITLE
[BUG] Build fail with new SmithyAPIGatewayTsProject

### ISSUE THREAD

**Issue by codypenta** [aws/aws-pdk#172]
### Describe the bug

Steps to reproduce:

1. Gen project with: `npx projen new --from aws-prototyping-sdk nx-monorepo`
2. Add a SmithyAPIGatewayTsProject to `.projenrc.ts`:

```typescript
new SmithyApiGatewayTsProject({
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  defaultReleaseBranch: "main",
  name: "api",
  parent: monorepo,
  outdir: "packages/api",
});
```

3. Run `npx projen && npx nx run-many --target=build --all`

Outcome:

projen default command fails (ts-node --project tsconfig.dev.json .projenrc.ts) however, it looks like a subcommand failed instead:

```bash
# Command formated
Error: Command failed: ./gradlew \ 
  -p /prototype/packages/api/smithy-build generate \
  -Pconfig=/prototype/packages/api/smithy-build/smithy-build.json \
  -Pdiscover=/prototype/packages/api/model \
  -Poutput=/prototype/packages/api/smithy-build/output
```
```bash
FAILURE: Build failed with an exception.

* What went wrong:
Could not open cp_settings generic class cache for settings file 'prototype/packages/api/smithy-build/settings.gradle' (/Users/cpenta/.gradle/caches/7.5.1/scripts/1b8lfqt0kt3e5yt7t7grdr4rh).
> BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 63
```
Inside of the `settings.gradle` file is only the autogenerated content:

```gradle
# settings.gradle
pluginManagement {
    plugins {
        id 'software.amazon.smithy' version '0.6.0'
    }
}
```

Welp...figured out the issue while describing it. Good rubber duck...Will comment with resolution and close

### Expected Behavior

See resolution

### Current Behavior

See resolution

### Reproduction Steps

See resolution

### PDK version used

0.11.3

### Environment details (OS name and version, etc.)

MacOS

**Comment by codypenta** [comment]
New age kid trying to run Java Corretto 19. Moving back to LTS Java Corretto 17 resolved the issue.

**Comment by cogwirrel** [comment]
Thanks for raising this and great stuff getting to the bottom of it! :)

Looks like grade support for JDK 19 is being tracked here: https://github.com/gradle/gradle/issues/20372

As a related note in case you encounter this, some users have had difficulty with the open api generator step with JDK 17 - I’ve been using Corretto 11 which has been working well!
