### ISSUE TITLE
[FEATURE] Smithy generated Server SDK (SSDK) for TS

### ISSUE THREAD

**Issue by codypenta** [aws/aws-pdk#177]
### Describe the feature

It looks like we generate types and values from OpenAPI tools. It would be nice to generate types, validators, etc using Smithy tools. Right now, it looks like most are unstable with the exception of typescript, which is in preview:

- https://aws.amazon.com/blogs/devops/smithy-server-and-client-generator-for-typescript/
- https://awslabs.github.io/smithy/2.0/ts-ssdk/index.html
- https://github.com/aws-samples/smithy-server-generator-typescript-sample

### Use Case

From previous experiences, the code generation tends to be better coming from a Smithy Model vs going from Smithy -> OpenAPI -> OpenAPITools but not in any *drastic* way.

### Proposed Solution

By default, a SmithyApiGatewayTsProject would use smithy code generation, but you can opt-in to OpenAPI generation

```ts
const api = new SmithyApiGatewayTsProject({
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  defaultReleaseBranch: "main",
  name: "api",
  parent: monorepo,
  useOpenAPIGen: true, // <-- new flag
  outdir: "packages/api",
  serviceName: "aws.bumpercars#Bumpercars",
  deps: [
    "@aws-lambda-powertools/logger",
    "@aws-lambda-powertools/tracer",
    "@aws-lambda-powertools/metrics",
  ],
});
```

### Acknowledgements

- [X] I may be able to implement this feature request
- [X] This feature might incur a breaking change

### PDK version used

0.11.3

### What languages will this feature affect?

Typescript

### Environment details (OS name and version, etc.)

MacOS

**Comment by codypenta** [comment]
On this, it looks like the Smithy stuff is exported as well so I was able to make a `packages/model` and `packages/codegen`


```typescript
new SmithyModelProject({
  name: "model",
  outdir: "packages/model",
  serviceName: "Bumpercars",
  serviceNamespace: "aws.bumpercars",
  parent: monorepo
})

new SmithyBuildProject({
  buildOutputDir: "codegen",
  fullyQualifiedServiceName: "aws.bumpercars#Bumpercars",
  modelPath: "../model/main.smithy",
  name: "codegen",
  parent: monorepo,
  outdir: "packages/codegen",
  smithyBuildOptions: {
    plugins: {
      "typescript-codegen": {
        "service": "aws.bumpercars#Bumpercars",
        "targetNamespace": "Configuration",
        "package": "configuration",
        "packageVersion": "0.0.1",
        "packageJson": {
          "license": "Apache-2.0"
        }
      },
      "typescript-ssdk-codegen" : {
        "package" : "@smithy-bumpercars/bumpercars-service-ssdk",
        "packageVersion": "0.0.1"
      }
    },
  }
})
```

This builds all of the code....but I'm still trying to understand how to import it into a `packages/infra` app. But I believe that's more of a node packagement/tsconfig issue.

**Comment by cogwirrel** [comment]
Thanks for raising this!

Given that we make use of custom mustache templates to generate types used by the CDK construct I don't think we can omit the OpenAPI code generation entirely and use Smithy code generation as a stand-in replacement without quite a bit of effort. I'm not sure how easily customiseable Smithy code generators are, and we also need to support Java and Python which do not have Smithy code generators that I can see: https://awslabs.github.io/smithy/2.0/implementations.html#client-code-generators

It's definitely an intention of ours to allow users to make use of Smithy's code generation however! :) You can actually pass `smithyBuildOptions` to the `SmithyApiGatewayTsProject` to add your own projections/plugins for code generation ([documenation here](https://aws.github.io/aws-prototyping-sdk/typescript/open-api-gateway/index.html#@aws-prototyping-sdk/open-api-gateway.SmithyApiGatewayTsProjectOptions.property.smithyBuildOptions)), so you don't need to use `SmithyModelProject` and `SmithyBuildProject` directly. The projections are written to the `smithy-build/output` directory which is ignored in the `.gitignore` by default, so you'd need to also specify `ignoreSmithyBuildOutput: false` to customise what should be checked in.

With regards to making it importable, it needs to be included as part of the yarn/npm/pnpm workspace (eg the `workspaces` section of `package.json` for yarn). Right now the NX Monorepo doesn't let you customise this since this is currently generated automatically based on projects which specify `parent: monorepo`. It shouldn't be too hard to add in - will do so shortly and circle back here with an example!

**Comment by cogwirrel** [comment]
Now that the monorepo supports adding custom package paths to the workspace, you can include Smithy generated code in the monorepo using `monorepo.addWorkspacePackages('path/to/generated/package')`!

Here's a working example `.projenrc.ts`:

```ts
import { nx_monorepo } from "aws-prototyping-sdk";
import { ClientLanguage, SmithyApiGatewayTsProject } from "@aws-prototyping-sdk/open-api-gateway";

const monorepo = new nx_monorepo.NxMonorepoProject({
  defaultReleaseBranch: "main",
  devDeps: ["aws-prototyping-sdk", "@aws-prototyping-sdk/open-api-gateway"],
  name: "smithy-ssdk-demo",
});

const api = new SmithyApiGatewayTsProject({
  parent: monorepo,
  outdir: 'packages/api',
  name: 'api',
  defaultReleaseBranch: 'main',
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  // So that we can check in the generated SSDK
  ignoreSmithyBuildOutput: false,
  // Add a projection for generating the SSDK. Note that this can only be added once the `smithy-build/build.gradle` has
  // been updated with the appropriate dependencies. In my test example I added the following extras:
  // smithy("software.amazon.smithy:smithy-validation-model:1.24.0")
  // smithy("software.amazon.smithy.typescript:smithy-typescript-codegen:0.11.0")
  // smithy("software.amazon.smithy.typescript:smithy-aws-typescript-codegen:0.11.0")
  smithyBuildOptions: {
    projections: {
      'ts-ssdk': {
        plugins: {
          'typescript-ssdk-codegen': {
            package: 'my-tssdk',
            packageVersion: '0.0.1',
          },
        },
      },
    },
  },
  // NB this dependency must be added in a subsequent pass of `npx projen`, after adding the projection
  // and the package path to the monorepo
  deps: ['my-tssdk@0.0.1'],
});

// We ignore projections other than the generated Smithy SSDK
api.gitignore.addPatterns('smithy-build/output/openapi', 'smithy-build/output/source');

// Add the generated Smithy TypeScript Server SDK to the monorepo such that we can depend on it
monorepo.addWorkspacePackages('packages/api/smithy-build/output/ts-ssdk/typescript-ssdk-codegen');

monorepo.synth();
```

In this example, I added the dependency to the `api` package but you can add it to any other package in your monorepo instead. NX will automatically pick up the package, so it'll be included in the build when you run `npx nx run-many --target build --all`, and NX will build it in the correct dependency order.

I hope this helps! Feel free to reopen if you have any issues! :)

**Comment by codypenta** [comment]
I may be getting the order of operations wrong trying to replicate:

Step 1 (`npx projen` the "skeleton"):

```typescript
const api = new SmithyApiGatewayTsProject({
  parent: monorepo,
  outdir: "packages/api",
  name: "api",
  defaultReleaseBranch: "main",
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  serviceName: { serviceName: "Bumpercars", namespace: "aws.bumpercars" },
  // So that we can check in generated SSDK
  ignoreSmithyBuildOutput: false,
  // Add a projection for generating the SSDK. Note that this can only be added once the `smithy-build/build.gradle` has
  // been updated with the appropriate dependencies.
  // smithy("software.amazon.smithy:smithy-validation-model:1.24.0")
  // smithy("software.amazon.smithy:smithy-aws-apigateway-openapi:1.24.0")
  // smithy("software.amazon.smithy.typescript:smithy-typescript-codegen:0.12.0")
  // smithy("software.amazon.smithy.typescript:smithy-aws-typescript-codegen:0.12.0"),
  // smithyBuildOptions: {
  //   projections: {
  //     "ts-ssdk": {
  //       plugins: {
  //         "typescript-ssdk-codegen": {
  //           package: "bumpercars-tssdk",
  //           packageVersion: "0.0.1",
  //         },
  //       },
  //     },
  //   },
  // },
  // NB this dependency must be added in a subsequent pass of `npx projen`, after adding the projection
  // and the package path to the monorepo
  // deps: [
  //   "bumpercars-tssdk@0.0.1",
  //   "@aws-smithy/server-common",
  //   "@aws-smithy/server-apigateway",
  // ],
});
// We ignore projections other than the generated Smithy SSDK
api.gitignore.addPatterns(
  "smithy-build/output/openapi",
  "smithy-build/output/source"
);

// Add the generated Smithy Typescript Server SDK to the monorepo such that we can depend on it
// monorepo.addWorkspacePackages(
//   "packages/api/smithy-build/output/ts-ssdk/typescript-ssdk-codegen"
// );
```

Step 2 (Update Smithy model in `packages/api/model/main.smithy` and build settings in `packages/api/smithy-build/build.gradle`):

```groovy
dependencies {
    smithy("software.amazon.smithy:smithy-cli:1.24.0")
    smithy("software.amazon.smithy:smithy-model:1.24.0")
    smithy("software.amazon.smithy:smithy-openapi:1.24.0")
    smithy("software.amazon.smithy:smithy-aws-traits:1.24.0")
    smithy("software.amazon.smithy:smithy-validation-model:1.24.0")
    smithy("software.amazon.smithy:smithy-aws-apigateway-openapi:1.24.0")
    smithy("software.amazon.smithy.typescript:smithy-typescript-codegen:0.11.0")
    smithy("software.amazon.smithy.typescript:smithy-aws-typescript-codegen:0.11.0"),
}
```

Step 3 (`npx projen` while uncommenting the smithy-build config)

```typescript
const api = new SmithyApiGatewayTsProject({
  parent: monorepo,
  outdir: "packages/api",
  name: "api",
  defaultReleaseBranch: "main",
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  serviceName: { serviceName: "Bumpercars", namespace: "aws.bumpercars" },
  // So that we can check in generated SSDK
  ignoreSmithyBuildOutput: false,
  // Add a projection for generating the SSDK. Note that this can only be added once the `smithy-build/build.gradle` has
  // been updated with the appropriate dependencies.
  // smithy("software.amazon.smithy:smithy-validation-model:1.24.0")
  // smithy("software.amazon.smithy:smithy-aws-apigateway-openapi:1.24.0")
  // smithy("software.amazon.smithy.typescript:smithy-typescript-codegen:0.11.0")
  // smithy("software.amazon.smithy.typescript:smithy-aws-typescript-codegen:0.11.0")
  smithyBuildOptions: {
    projections: {
      "ts-ssdk": {
        plugins: {
          "typescript-ssdk-codegen": {
            package: "bumpercars-tssdk",
            packageVersion: "0.0.1",
          },
        },
      },
    },
  },
  // NB this dependency must be added in a subsequent pass of `npx projen`, after adding the projection
  // and the package path to the monorepo
  // deps: [
  //   "bumpercars-tssdk@0.0.1",
  //   "@aws-smithy/server-common",
  //   "@aws-smithy/server-apigateway",
  // ],
});
// We ignore projections other than the generated Smithy SSDK
api.gitignore.addPatterns(
  "smithy-build/output/openapi",
  "smithy-build/output/source"
);

// Add the generated Smithy Typescript Server SDK to the monorepo such that we can depend on it
// monorepo.addWorkspacePackages(
//   "packages/api/smithy-build/output/ts-ssdk/typescript-ssdk-codegen"
// );
```

Step 4 (`npx projen` while uncommenting monorepo.packagePath):

```ts
// Add the generated Smithy Typescript Server SDK to the monorepo such that we can depend on it
monorepo.addWorkspacePackages(
  "packages/api/smithy-build/output/ts-ssdk/typescript-ssdk-codegen"
);
```

Confirmed in `package.json`:

```json
  "workspaces": {
    "packages": [
      "packages/api",
      "packages/api/generated/typescript",
      "packages/api/smithy-build/output/ts-ssdk/typescript-ssdk-codegen"
    ]
  },
```

Step 5 (`npx projen` while uncommenting deps)

```typescript
const api = new SmithyApiGatewayTsProject({
  parent: monorepo,
  outdir: "packages/api",
  name: "api",
  defaultReleaseBranch: "main",
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  serviceName: { serviceName: "Bumpercars", namespace: "aws.bumpercars" },
  // So that we can check in generated SSDK
  ignoreSmithyBuildOutput: false,
  // Add a projection for generating the SSDK. Note that this can only be added once the `smithy-build/build.gradle` has
  // been updated with the appropriate dependencies.
  // smithy("software.amazon.smithy:smithy-validation-model:1.24.0")
  // smithy("software.amazon.smithy:smithy-aws-apigateway-openapi:1.24.0")
  // smithy("software.amazon.smithy.typescript:smithy-typescript-codegen:0.11.0")
  // smithy("software.amazon.smithy.typescript:smithy-aws-typescript-codegen:0.11.0"),
  smithyBuildOptions: {
    projections: {
      "ts-ssdk": {
        plugins: {
          "typescript-ssdk-codegen": {
            package: "bumpercars-tssdk",
            packageVersion: "0.0.1",
          },
        },
      },
    },
  },
  // NB this dependency must be added in a subsequent pass of `npx projen`, after adding the projection
  // and the package path to the monorepo
  deps: [
    "bumpercars-tssdk@0.0.1",
    // "@aws-smithy/server-common",
    // "@aws-smithy/server-apigateway",
  ],
});
```

This is where it fails, it looks like yarn is still wanting to look for the pacakge `bumpercars-tssdk` in a registry that is not local.


Ahh, I see what it is. I'm missing the `npx nx run-many --target build --all` before step 5.

**Comment by cogwirrel** [comment]
Nice! Great to hear that worked! 😁

**Comment by codypenta** [comment]
Looks like there is a subtle ordering bug, everytime I `npx projen`, it is wanting to write the order (in package.json) as:

```json
  "workspaces": {
    "packages": [
      "packages/api",
      "packages/api/generated/typescript",
      "packages/infra",
      "packages/api/smithy-build/output/ts-ssdk/typescript-ssdk-codegen"
    ]
  },
```

Because the typescript-ssdk-codegen appears after, yarn is wanting to go back out to the repo before looking locally. When manually changing `package.json` to put infra last. It works fine.

The code that generated it:

```typescript
const api = new SmithyApiGatewayTsProject({
  parent: monorepo,
  outdir: "packages/api",
  name: "api",
  defaultReleaseBranch: "main",
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  serviceName: { serviceName: "Bumpercars", namespace: "aws.bumpercars" },
  // So that we can check in generated SSDK
  ignoreSmithyBuildOutput: false,
  // Add a projection for generating the SSDK. Note that this can only be added once the `smithy-build/build.gradle` has
  // been updated with the appropriate dependencies.
  // smithy("software.amazon.smithy:smithy-validation-model:1.24.0")
  // smithy("software.amazon.smithy:smithy-aws-apigateway-openapi:1.24.0")
  // smithy("software.amazon.smithy.typescript:smithy-typescript-codegen:0.11.0")
  // smithy("software.amazon.smithy.typescript:smithy-aws-typescript-codegen:0.11.0"),
  smithyBuildOptions: {
    projections: {
      "ts-ssdk": {
        plugins: {
          "typescript-ssdk-codegen": {
            package: "bumpercars-tssdk",
            packageVersion: "0.0.1",
          },
        },
      },
    },
  },
  // NB this dependency must be added in a subsequent pass of `npx projen`, after adding the projection
  // and the package path to the monorepo
  deps: [
    cdkVersion,
    constructVersion,
    "bumpercars-tssdk@0.0.1",
    "@aws-lambda-powertools/commons",
    "@aws-lambda-powertools/logger",
    "@aws-lambda-powertools/metrics",
    "@aws-lambda-powertools/tracer",
    "@aws-sdk/client-s3",
    "@aws-smithy/server-apigateway",
    "@aws-smithy/server-common",
    "@middy/core",
    "@types/aws-lambda",
  ],
  devDeps: ["aws-sdk-client-mock"],
});

// Add the generated Smithy Typescript Server SDK to the monorepo such that we can depend on it
monorepo.addWorkspacePackages(
  "packages/api/smithy-build/output/ts-ssdk/typescript-ssdk-codegen"
);

new AwsCdkTypeScriptApp({
  parent: monorepo,
  outdir: "packages/infra",
  name: "infra",
  defaultReleaseBranch: "main",
  cdkVersion: cdkVersion.split("@")[1].replace("^", ""),
  deps: [
    api.package.packageName,
    constructVersion,
    "@types/js-yaml",
    "js-yaml",
    "cdk-nag",
  ],
});
```

I was looking for some way to enforce ordering like you can in the CDK, but it doesn't look like projen projects have a `node.addDependsOn` function. Right now, it's a manual escape hatch.

```typescript
// Escape hatch until further investigation: https://github.com/aws/aws-prototyping-sdk/issues/177
const packageJson = monorepo.tryFindObjectFile("package.json");
packageJson?.addOverride("workspaces.packages", [
  "packages/api",
  "packages/api/generated/typescript",
  "packages/api/smithy-build/output/ts-ssdk/typescript-ssdk-codegen",
  "packages/infra",
]);
```

(side note to self: Look into PDK nag)

**Comment by cogwirrel** [comment]
Ah that's interesting! I wasn't aware that the order of the packages in the yarn workspace definition mattered! Currently `workspaces.packages` are generated with subprojects first (in alphabetical project name order) followed by the additional dependencies.

The ideal would be to put them in dependency order - for that we have a mixture of "implicit dependencies" which we know about in the projen project itself, but the typescript dependencies are a bit trickier to infer. There's a `ProjectGraphBuilder` from NX which we can use to get the order of all dependencies - but that relies on all the projects having already synth'd because it infers dependencies based on package.json files and the yarn workspace itself! 🐓🥚

It looks like projen's `subprojects` are in the order in which the constructors were called which may be a good approximation of dependency order (at least better than alphabetical project name order) - so using that might work ok - the only challenge would be inserting the additional dependencies in the right order relative to the subprojects. The simple solution would be to just have those added in the monorepo constructor rendered first, and then those added via `addWorkspacePackages` added last. A more complex but customiseable method might be to allow you to "slot in" the additional packages between the subprojects based on when the call to `addWorkspacePackages` occurs relative to constructing subprojects... I'll play around and see if I can get something a bit more intuitive working. Great that there's a workaround at least!

**Comment by cogwirrel** [comment]
With #189 you can control the order of `workspaces.packages` in a non escape-hatch way :)

So as long as you call `addWorkspacePackages` prior to creating the `AwsCdkTypeScriptApp` (which you do already), that order will be reflected in the `package.json`.
