### ISSUE TITLE
[BUG] Cannot use api test console when using lambda integration

### ISSUE THREAD

**Issue by AndreaCatalucciTractable** [aws/aws-pdk#178]
### Describe the bug

Since https://github.com/aws/aws-prototyping-sdk/blob/mainline/packages/open-api-gateway/src/construct/integrations/integrations.ts#L260 grants access only to the deployment stage, the api gateway test console (which uses a stage named "test-invoke-stage") fails invoking any lambda with an error `Execution failed due to configuration error: Invalid permissions on Lambda function`

I suggest either adding this stage to the lambda resource policy generated, or using a "*" for stage name in the same way api gateway does when associating a lambda with a method

### Expected Behavior

I can invoke a lambda integration through the AWS Api gateway test console

### Current Behavior

The lambda fails with "Invalid permissions on Lambda function"

### Reproduction Steps

Generate an api gateway with a lambda integration using the @aws-prototyping-sdk/open-api-gateway module

### Possible Solution

I submitted a [PR](https://github.com/aws/aws-prototyping-sdk/pull/180) changing from the specific stage to a star permission for the lambda integration

### PDK version used

0.11.4

### Environment details (OS name and version, etc.)

Any

**Comment by cogwirrel** [comment]
Thanks for raising this and for your PR!
