### ISSUE TITLE
[BUG] API Gateway `ANY` type is not supported

### ISSUE THREAD

**Issue by codypenta** [aws/aws-pdk#179]
### Describe the bug

I am, unfortunately, porting over some code that uses API gateway's `ANY` type for HTTP methods as the actual Lambda does function level routing based on the HTTP method passed in.

Since the underlying OpenAPI generator does not support it [Operations](https://swagger.io/docs/specification/paths-and-operations/). This causes a silent build fail when specifying it in a smithy model

```smithy
@http(method: "ANY", uri: "/configure")
operation Configure {
    input: ConfigureInput,
    output: ConfigureOutput,
    errors: [ValidationException]
}
```

### Expected Behavior

Build or throw hard fail when `@http(method: "ANY")` is encountered.

### Current Behavior

Silenty fails until typescript throws an error that it cannot find a `configureHandler` since one was not built.

### Reproduction Steps

Should be any operation with `@http(method: "ANY")`

### Possible Solution

Not sure if Smithy's typescript SSDK would solve this? For me, I'm simply going to port the code to use standard HTTP methods and routing at the API gateway level, but wanted to document this.

### PDK version used

0.11.4

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

MacOS

**Comment by cogwirrel** [comment]
Good catch! I'll raise a PR to add validation rather than silently omit the operation.
