### ISSUE TITLE
Feature: support PDKProject nx configuration and improve nx caching

### ISSUE THREAD

**Issue by JeremyJonas** [aws/aws-pdk#215]
Currently [nx input/output configuration](https://nx.dev/more-concepts/customizing-inputs) is only configurable for all projects with a default set which is managed by the `pdk-monorepo-project` itself. However many packages variant/additional "input" and/or "output" paths that if defined would benefit from more targeted caching control.

### Current implementation
https://github.com/aws/aws-prototyping-sdk/blob/ac6c3aff0e92e6b9f9a264120a17f91f4646339c/private/projects/pdk-monorepo-project.ts#L193-L212

#### `packages/aws-arch`

* **Input**
  * /scripts
  * /src
  * !/src/generated (exclude this) 

* **Output**
  * /assets
  * /dist
  * /lib
  * /src/generated

<img width="417" alt="image" src="https://user-images.githubusercontent.com/464119/202937944-4d4a0a31-e7fb-4d1e-bf0e-28c9c461450f.png">

---
Additionally looks like `test-reports` should be added to default **Outputs**.

Also worth discussion, should we split out "build" and "test" target *input / output* configurations? I know that **build** currently calls **test**, but would consider separating these to benefit from nx caching. To this extends, what about separating out *pre-compile*, *compile*, etc.... so they can all be cached. This would require ensuring that nx run is utilized as well throughout to enable caching behaivor.

**Comment by JeremyJonas** [comment]
Additionally if we applied more granular task caching, we could get rid of package specific caching, such as is being done for `aws-arch` asset generation which is currently using "lazy generate". We could just remove this "lazy" task wrapper and utilize nx caching.

**Comment by agdimech** [comment]
This has been resolved as part of #216
