### ISSUE TITLE
[BUG] npm ERR! This command does not support workspaces

### ISSUE THREAD

**Issue by pchaganti** [aws/aws-pdk#229]
### Describe the bug

Setup a nx-monorepo that uses a subproject of type ```AwsCdkConstructLibrary```.

Running ```npm set //npm.pkg.github.com/:_authToken $GITHUB_PACKAGER_TOKEN && npm publish``` in a task results in the error:

```
� package-all » package:js | jsii-pacmak -v --target js
       [jsii-pacmak] [INFO] Found 1 modules to package
       [jsii-pacmak] [INFO] Packaging NPM bundles
       [jsii-pacmak] [INFO] Loading jsii assemblies and translations
       [jsii-pacmak] [INFO] Packaging 'js' for test_project
       [jsii-pacmak] [INFO] js finished
       [jsii-pacmak] [INFO] Packaged. load jsii (0.7s) | npm pack (0.4s) | js (0.0s) | cleanup (???)
      
� releaser » unbump | /home/ec2-user/.nvm/versions/node/v16.14.2/bin/node /home/ec2-user/environment/test_project/node_modules/projen/lib/release/reset-version.task.js

� releaser | npm set //npm.pkg.github.com/:_authToken $PACKAGER_TOKEN && npm publish
       npm ERR! code ENOWORKSPACES
       npm ERR! This command does not support workspaces.
```

### Expected Behavior

npm command should work without error.

### Current Behavior

```
npm ERR! code ENOWORKSPACES
npm ERR! This command does not support workspaces.
```

### Reproduction Steps

Attached a test repo. node modules removed for size reasons.

- Run yarn install
- Run npx nx run-many --target=releaser --all

[test_projen.zip](https://github.com/aws/aws-prototyping-sdk/files/10132665/test_projen.zip)

### Additional Information/Context

```
npm -v
8.15.0
```

### PDK version used

0.12.20

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Linux x86_64

**Comment by agdimech** [comment]
Are you able to determine whether this is failing on the `npm set` or `npm publish` step?

**Comment by pchaganti** [comment]
i removed the npm set to test this. Fails on npm publish.

**Comment by agdimech** [comment]
Tested locally using npm@8.19.2 and am seeing the error being thrown while calling npm set as you need to call `npm config set`. To work around this I have listed 3 options below with option 1 being least recommended and option 3 being most recommended.

**Option 1: Inline**
Change the releaser script as follows:

```
npm config set //npm.pkg.github.com/:_authToken $GITHUB_PACKAGER_TOKEN && npm config set registry=https://npm.pkg.github.com && npm publish --no-workspaces

```

**Option 2: Project specific .npmrc**
Add a .npmrc file in base/cdk-projen-test as follows:

```
//npm.pkg.github.com/:_authToken=$GITHUB_PACKAGER_TOKEN
registry=https://npm.pkg.github.com
```

Change releaser script as follows: `npm publish --no-workspaces`

**Option 3: Workspace specific .npmrc**
Add a .npmrc file in the root of the monorepo as follows:

```
//npm.pkg.github.com/:_authToken=$GITHUB_PACKAGER_TOKEN
registry=https://npm.pkg.github.com
```

Change releaser script as follows: `npm publish`

Please feel free to re-open if you feel this has no adequately addressed your issue.

**Comment by pchaganti** [comment]
Thank you!
