### ISSUE TITLE
[BUG] additionalInterceptors is not iterable

### ISSUE THREAD

**Issue by phstc** [aws/aws-pdk#258]
### Describe the bug

I'm following the steps [here](https://www.youtube.com/watch?v=P4JoAjzMW08), and after deploying my stack and trying to run `awscurl` my lambda is failing with:

```
ERROR	Invoke Error 	
{
    "errorType": "TypeError",
    "errorMessage": "additionalInterceptors is not iterable",
    "stack": [
        "TypeError: additionalInterceptors is not iterable",
        "    at Runtime.handler (/var/task/index.js:504:42)",
        "    at Runtime.handleOnceNonStreaming (/var/runtime/Runtime.js:74:25)"
    ]
}
```

All `additionalInterceptors` references are generated. It is not something I added explicitly in my code.

My lambda implementation:

```typescript
export const handler = sayHelloHandler(async ({ input }) => {
  return {
    statusCode: 200,
    headers: {
      "Access-Control-Allow-Origin": "*",
      "Access-Control-Allow-Headers": "*",
    },
    body: {
      message: `Hello ${input.requestParameters.name}!`,
    },
  };
});
```

### Expected Behavior

Lambda should not with generated boilerplate code. 

### Current Behavior

Fail with `additionalInterceptors is not iterable`

### Reproduction Steps

1. Set up a new `npx projen new --from  aws-prototyping-sdk nx-monorepo`
2. Add API and infra

```typescript
import {
  ClientLanguage,
  DocumentationFormat,
  SmithyApiGatewayTsProject,
} from "@aws-prototyping-sdk/open-api-gateway";
import { nx_monorepo } from "aws-prototyping-sdk";
import { AwsCdkTypeScriptApp } from "projen/lib/awscdk";

const monorepo = new nx_monorepo.NxMonorepoProject({
  defaultReleaseBranch: "main",
  devDeps: ["aws-prototyping-sdk", "@aws-prototyping-sdk/open-api-gateway"],
  name: "project",
});

const api = new SmithyApiGatewayTsProject({
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  defaultReleaseBranch: "main",
  documentationFormats: [DocumentationFormat.HTML2],
  name: "api",
  parent: monorepo,
  outdir: "packages/api",
  serviceName: {
    namespace: "com.project",
    serviceName: "ApiService",
  },
});

new AwsCdkTypeScriptApp({
  defaultReleaseBranch: "main",
  parent: monorepo,
  outdir: "packages/infra",
  name: "infra",
  cdkVersion: "2.1.0",
  deps: [api.package.packageName],
});


monorepo.synth();

```

3. Update infra to include SampleApi

```typescript
new SampleApi(this, "sample-api");
```

4. awscurl `awscurl --service execute-api --region us-east-1  https://[ID].execute-api.us-east-1.amazonaws.com/prod/hello\?name\=boooo`

### PDK version used

0.12.33

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

macOS Monterey Version 12.5

**Comment by cogwirrel** [comment]
Good catch! With the recent handler router change it seems I broke the standalone handler wrappers. Looks like since the lambda handler is called with `(event, context, callback)`, the default value for `additionalInterceptors` is not being used!

I'll publish a PR to fix this ASAP!

In the mean time, feel free to either downgrade to [0.12.24](https://github.com/aws/aws-prototyping-sdk/releases/tag/v0.12.24), or make use of the `handlerRouter` ([docs here](https://github.com/aws/aws-prototyping-sdk/tree/mainline/packages/open-api-gateway#handler-router)) instead.

**Comment by phstc** [comment]
@cogwirrel thank you for the quick reply. 

> or make use of the handlerRouter ([docs here](https://github.com/aws/aws-prototyping-sdk/tree/mainline/packages/open-api-gateway#handler-router)) instead.

that worked.

**Comment by cogwirrel** [comment]
The fix is available in [0.12.34](https://github.com/aws/aws-prototyping-sdk/releases/tag/v0.12.34) - let me know if you have any other issues! :)

**Comment by phstc** [comment]
Hi @cogwirrel 

Thanks for the quick fix. I want to replace the `handlerRouter` with your fix. How would you update `.projenrc.ts` to use `0.12.34`? 

My .projenrc.ts

```typescript
import {
  ClientLanguage,
  DocumentationFormat,
  SmithyApiGatewayTsProject,
} from "@aws-prototyping-sdk/open-api-gateway";
import { nx_monorepo } from "aws-prototyping-sdk";
import { AwsCdkTypeScriptApp } from "projen/lib/awscdk";

const monorepo = new nx_monorepo.NxMonorepoProject({
  defaultReleaseBranch: "main",
  devDeps: ["aws-prototyping-sdk", "@aws-prototyping-sdk/open-api-gateway"],
  name: "project",
});

const api = new SmithyApiGatewayTsProject({
  clientLanguages: [ClientLanguage.TYPESCRIPT],
  defaultReleaseBranch: "main",
  documentationFormats: [DocumentationFormat.HTML2],
  name: "api",
  parent: monorepo,
  outdir: "packages/api",
  serviceName: {
    namespace: "com.project",
    serviceName: "ApiService",
  },
});

new AwsCdkTypeScriptApp({
  defaultReleaseBranch: "main",
  parent: monorepo,
  outdir: "packages/infra",
  name: "infra",
  cdkVersion: "2.1.0",
  deps: [api.package.packageName],
});


monorepo.synth();
```

**Comment by cogwirrel** [comment]
Hey @phstc 

No worries! There are a couple of different options - you could either specify the version in your `.projenrc.ts`, eg:

```ts
devDeps: ["aws-prototyping-sdk@^0.12.34", "@aws-prototyping-sdk/open-api-gateway@^0.12.34"],
```

Or, you can update the `package.json` files (either manually or with a tool like [npm-check-updates](https://www.npmjs.com/package/npm-check-updates)) as projen won't change the versions in the `package.json` when they're not specified in your `.projenrc.ts`.

Hope that helps!

Cheers,
Jack
