### ISSUE TITLE
[FEATURE] add email/SMS/TOTP option to Identity construct

### ISSUE THREAD

**Issue by sperka** [aws/aws-pdk#301]
### Describe the feature

Currently `Identity` construct provides SMS MFA out of the box, and also takes a `UserPool` parameter to enable customization. With this feature, we could enable 3 types of MFAs:

1. SMS (as is now)
2. TOTP - to use an authenticator app
3. email-based - receive temporary passcode through provided email

### Use Case

SMS works most of the time, however, in some countries (e.g.: Vietnam) SNS doesn't support certain telco providers. With this feature we could provide a broader coverage for customer requirements out of the box.

### Proposed Solution

Add an enum parameter with 3 values: `SMS` / `TOTP` / `Email` in the `Identity` constructor and the optional parameters for the selected MFA. By default, `SMS` is selected.

We could also introduce `smsOptions`, `totpOptions` and `emailOptions` optional parameters with their custom parameters if needed.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PDK version used

*

### What languages will this feature affect?

Typescript

### Environment details (OS name and version, etc.)

MacOS

**Comment by agdimech** [comment]
Good suggestion - we will be re-working the identity construct and will definitely be supporting these.

**Comment by agdimech** [comment]
Resolved in https://github.com/aws/aws-prototyping-sdk/pull/354
