### ISSUE TITLE
[BUG] Docker Daemon not running while deploying using PDK Stack

### ISSUE THREAD

**Issue by jyotisharma7** [aws/aws-pdk#309]
### Describe the bug

I created a PDK project with Lambda functions. Locally the project builds successfully as the docker-desktop is running. But when I try to deploy it using CodePipeline then it gives me the below error:
```
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
docker exited with status 1
```
I tries adding the below parameters in **pipeline-stack.ts** file inside **PDKPipeline** but still the issue did'nt get resolved.
```
dockerEnabledForSynth: true,
      dockerEnabledForSelfMutation: true,
      codeBuildDefaults: {
        buildEnvironment: {
          privileged: true,
        },
      },
```
After that I had to manually switch on the **Priviledged** option in **Environment** of Code Build to build Docker images.

### Expected Behavior

Priviledged option for docker should be enabled by default as part of PDK project.

### Current Behavior

The priviledged option has to be manually enabled in CodeBuild.

### Reproduction Steps

git add -A
git commit -m "fixes"
git push -u origin mainline

### PDK version used

0.14.10

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

MAC 13.2.1

**Comment by agdimech** [comment]
Did you pass these in the `synthCodeBuildDefaults` property?

**Comment by jyotisharma7** [comment]
I added those properties in pipeline-stack.ts. The code snippet is attached below.
```
this.pipeline = new PDKPipeline(this, "ApplicationPipeline", {
      primarySynthDirectory: "packages/cicd/cdk.out",
      repositoryName: this.node.tryGetContext("repositoryName") || "monorepo",
      publishAssetsInParallel: false,
      crossAccountKeys: true,
      synth: {},
      sonarCodeScannerConfig: this.node.tryGetContext("sonarqubeScannerConfig"),
      dockerEnabledForSynth: true,
      dockerEnabledForSelfMutation: true,
      codeBuildDefaults: {
        buildEnvironment: {
          privileged: true,
        },
      }
    });
```

**Comment by agdimech** [comment]
I think you need to change it to the following:

```
this.pipeline = new PDKPipeline(this, "ApplicationPipeline", {
      primarySynthDirectory: "packages/cicd/cdk.out",
      repositoryName: this.node.tryGetContext("repositoryName") || "monorepo",
      publishAssetsInParallel: false,
      crossAccountKeys: true,
      synth: {},
      sonarCodeScannerConfig: this.node.tryGetContext("sonarqubeScannerConfig"),
      dockerEnabledForSynth: true,
      dockerEnabledForSelfMutation: true,
      synthCodeBuildDefaults: {
        buildEnvironment: {
          privileged: true,
        },
      }
    });
```

Can you try that instead please?

**Comment by agdimech** [comment]
Any update on whether the posted change was able to resolve your issue?

**Comment by jyotisharma7** [comment]
Sorry for the late reply @agdimech , the above mentioned code snippet solved the docker problem. Thank you.

**Comment by agdimech** [comment]
No worries.
