### ISSUE TITLE
[nx-monorepo] Don't assume `dist/java` in `addJavaDependency`

### ISSUE THREAD

**Issue by cogwirrel** [aws/aws-pdk#362]
### Describe the bug

Once https://github.com/projen/projen/pull/2624 is released, we can use `project.packaging.distdir` instead of hardcoding `dist/java` in `addJavaDependency`.

### Expected Behavior

No hardcode

### Current Behavior

Hardcode!

### Reproduction Steps

.

### PDK version used

0.16.1

### What languages are you seeing this issue on?

Typescript, Java, Python

### Environment details (OS name and version, etc.)

osx

**Comment by agdimech** [comment]
Your fix is included in 0.71.20 so can update this PR now :)
