### ISSUE TITLE
[FEATURE] Github as source for PDK pipeline

### ISSUE THREAD

**Issue by rverma-dev** [aws/aws-pdk#368]
### Describe the feature

Provide support for Github as source for PDK pipeline.

### Use Case

Code stored in Github

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PDK version used

0.17.0

### What languages will this feature affect?

Typescript

### Environment details (OS name and version, etc.)

Macos Arm

**Comment by agdimech** [comment]
Closing as this is already supported. Users can simply provide an "input" as part of `synthShellStepPartialProps` with a configured github repo.
