### ISSUE TITLE
[BUG] Error resolving versions of dependencies in a monorepo

### ISSUE THREAD

**Issue by zetashift** [aws/aws-pdk#379]
### Describe the bug

What initially started out as projen issue seems to affect `nx-monorepo` as well: https://github.com/projen/projen/issues/2641

When running `npx projen` I'm getting the following error as a result of a recent `projen` upgrade:

```
When running npx projen in my mono repo I'm getting the following error:

foo main• ↑4 ❱ npx projen                                         devenv-shell-env
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
👾 unable to resolve version for api-typescript-runtime from installed modules
👾 unable to resolve version for api-typescript-infra from installed modules
👾 unable to resolve version for api-typescript-runtime from installed modules
```

@mrgrain said the following:

> It pretty much comes down to this line:
> https://github.com/aws/aws-prototyping-sdk/blob/cf57586f2567a571c734606d6f003f6a5051bfca/packages/nx-monorepo/src/nx-monorepo.ts#L766
> 
> projen core now (correctly) expects that subproject dependencies are installed before resolveDepsAndWritePackageJson is called. Overwriting installDependencies on the subproject has been the go to way for monorepos to do this. But of course there's a reason that method is private.
> 
> I think what this highlights is the missing support for workspace-based monorepos in NodeProject.
> I wonder what the API for this should look like.

### Expected Behavior

The dependencies specified in subprojects being resolved.

### Current Behavior

The packages aren't available because the versions can't be resolved.

### Reproduction Steps

Create a new nx-monorepo

```
mkdir repo && npx projen new --from @aws-prototyping-sdk/nx-monorepo
```

Change the `project` variable in `.projenrc.ts` to this:

```typescript
const project = new NxMonorepoProject({
  defaultReleaseBranch: "main",
  devDeps: ["@aws-prototyping-sdk/nx-monorepo", "@aws-prototyping-sdk/type-safe-api"],
  name: "foo",
  projenrcTs: true,

  deps: [],                /* Runtime dependencies of this module. */
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // packageName: undefined,  /* The "name" in package.json. */
});
```

Then run `npx projen`.

Then change the .projenrc.ts to:

```typescript
import { NxMonorepoProject } from "@aws-prototyping-sdk/nx-monorepo";
import { AwsCdkTypeScriptApp } from "projen/lib/awscdk";
import {
  DocumentationFormat,
  Language,
  ModelLanguage,
  TypeSafeApiProject,
} from "@aws-prototyping-sdk/type-safe-api";

const project = new NxMonorepoProject({
  defaultReleaseBranch: "main",
  devDeps: ["@aws-prototyping-sdk/nx-monorepo", "@aws-prototyping-sdk/type-safe-api"],
  name: "foo",
  projenrcTs: true,

  deps: [],                /* Runtime dependencies of this module. */
  // description: undefined,  /* The description is just a string that helps people understand the purpose of the package. */
  // packageName: undefined,  /* The "name" in package.json. */
});


/** Contains all the smithy model files and codegenerates documentation, clients and API types.
 */
const api = new TypeSafeApiProject({
  name: "api",
  parent: project,
  outdir: "packages/api",
  runtime: {
    languages: [Language.TYPESCRIPT],
  },
  infrastructure: {
    language: Language.TYPESCRIPT,
  },
  documentation: {
    formats: [DocumentationFormat.HTML_REDOC],
  },
  model: {
    language: ModelLanguage.SMITHY,
    options: {
      smithy: {
        serviceName: {
          namespace: "foo.api",
          serviceName: "FooApi",
        },
      },
    },
  },
});

/** Our CDK based project that will deploy our API on AWS Lambda.
 * Also contains all the code for the Lambda handlers.
 */
new AwsCdkTypeScriptApp({
  name: "infra",
  parent: project,
  outdir: "packages/infra",
  defaultReleaseBranch: "main",
  cdkVersion: "2.76.0",
  deps: [
    api.runtime.typescript!.package.packageName,
    api.infrastructure.typescript!.package.packageName,
    "node-fetch",
  ],
  devDeps: [
  ],
  eslint: false,
  gitignore: ["edgeql-js"],
});

project.synth();
```

And run `npx projen` again. It should fail to resolve the dependencies of the `AwsCdkTypeScriptApp`

### Possible Solution

I'm not sure, but this seems like it might require an API change for `NodeProject`s.

### Additional Information/Context

See https://github.com/projen/projen/issues/2641 and the comments by mrgrain that highlight the way `projen` dealt with version resolution before and after the latest version release.

### PDK version used

0.17.4

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

MacOS ARM64 13.3.1

**Comment by mrgrain** [comment]
I think the easy fix here is to "disable" `resolveDepsAndWritePackageJson` on the subproject as well.
This should get us back to the state that we had before, effectively not resolving subproject dependencies.
Arguably it's even better than what we had before, because we now just bypass useless code.

```ts
subNodeProject.package.resolveDepsAndWritePackageJson = () => {}; 
```

--- 

I do have a somewhat complex solution that delegates dependency management to the root project. It consists of two parts.

In the monorepo root project, add the following:
```ts
class MonorepoProject extends NodeProject {
    private postInstallDependencies = new Array<() => boolean>();

    /**
     * Allows a sub project to request installation of dependency at the Monorepo root
     * They must provide a function that is executed after dependencies have been installed
     * If this function returns true, the install command is run for a second time after all sub project requests have run.
     * This is used to resolve dependency versions from `*` to a concrete version constraint.
     */
    requestInstallDependencies(resolver) {
        this.postInstallDependencies.push(resolver.resolveDepsAndWritePackageJson);
    }

  /**
   * Hooks into the install dependencies cycle
   */
  public postSynthesize() {
    if (this.postInstallDependencies.length) {
      const nodePkg: any = this.package;
      nodePkg.installDependencies();

      const completedRequests = this.postInstallDependencies.map((request) => request());
      if (completedRequests.some(Boolean)) {
        nodePkg.installDependencies();
      }

      this.postInstallDependencies = [];
    }
  }
}
```

Then for each subproject, we can delegate the installation and version resolution to the root project:
(I have this in the constructor of the subproject, but should be easy enough to do this from the root.)
```ts
class SubProject extends TypeScriptProject {
    public constructor(/* ... */)  {
        super(/* ... */);

        // Install dependencies via the parent project
        const orginalResolve = this.package.resolveDepsAndWritePackageJson;
        this.package.installDependencies = () => {
            options.root.requestInstallDependencies({ resolveDepsAndWritePackageJson: () => orginalResolve.apply(this.package) });
        };
        this.package.resolveDepsAndWritePackageJson = () => {};
    }
}
```

--- 

I'm looking to stabilize this as a public API. Seems like all Node workspace implementations pretty much work this way, so that should be fairly generic.
