### ISSUE TITLE
[BUG] (code catalyst reports include cached report)

### ISSUE THREAD

**Issue by mteichtahl** [aws/aws-pdk#413]
### Describe the bug

Code catalyst is not ignoring node_modules/.cached which contains test-reports

```node_modules/.cache/nx/3b3f674535ee4217684073f8403bf258d19c7ea4580caf69b4352ebff3ab3ec3/outputs/packages/infra/test-reports/junit.xml```

### Expected Behavior

Reports should not include cached reports

### Current Behavior

cached reports being included it code catalyst reports

### Reproduction Steps

Any build will generate this behavior

### PDK version used

latest

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

N/A

**Comment by agdimech** [comment]
Resolved in latest blueprint.
