### ISSUE TITLE
[DOCS] type-safe-api python example changes .projenrc.py to .projenrc.ts

### ISSUE THREAD

**Issue by jstrunk** [aws/aws-pdk#457]
### Describe the issue

I'm trying to use a type-safe-api and pipeline together in a python project. I was having trouble with dependencies, so I followed the example in the type-safe-api developer guide which shows to use nx-monorepo as well in my `.projenrc.py`. After running projen successfully, any other projen command fails with

```
👾 default | ts-node --project tsconfig.dev.json .projenrc.ts
node:internal/modules/cjs/loader:1078
  throw err;
  ^

Error: Cannot find module './.projenrc.ts'
```

### Links

https://aws.github.io/aws-prototyping-sdk/developer_guides/type-safe-api/index.html with the python tab.

**Comment by cogwirrel** [comment]
Thanks for catching this! `nx-monorepo` only supports using TypeScript to write your `.projenrc` at present, so the Python and Java `.projenrc` examples weren't accurate.

I'll update the docs with the `.projenrc` examples in TypeScript.
