### ISSUE TITLE
[BUG] pipeline: feature branch pipeline creation fails for bare PDKPipelinePyProject

### ISSUE THREAD

**Issue by jstrunk** [aws/aws-pdk#462]
### Describe the bug

I got a CDK CLI error during the creation of new pipelines for branches, however the main branch pipeline works.

`--app is required either in command-line, in cdk.json or in ~/.cdk.json`

### Expected Behavior

When a new branch is pushed, the CodeBuild project should create a new pipeline stack for the branch.

### Current Behavior

The CodeBuild project fails with

> [Container] 2023/06/06 21:30:38 Running command cd
> --
>  
> [Container] 2023/06/06 21:30:38 Running command cdk synth
> 
> --app is required either in command-line, in cdk.json or in ~/.cdk.json
> 
> [Container] 2023/06/06 21:30:38 Command did not exit successfully cdk synth exit status 1
> [Container] 2023/06/06 21:30:38 Phase complete: BUILD State: FAILED
> [Container] 2023/06/06 21:30:38 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: cdk synth. Reason: exit status 1

### Reproduction Steps

**.projenrc.py**
``` py
from aws_prototyping_sdk import pipeline

project = pipeline.PDKPipelinePyProject(
    author_email="mmmm@nnnn",
    author_name="mmmm",
    module_name="mmmm",
    name="mmmm",
    version="0.1.0",
    deps=["aws-prototyping-sdk.pipeline"],
    cdk_version="2.81.0",
    context={
        "repositoryName": "mmmm",
        "defaultBranchName": "main",
    },
)

project.synth()
```

**pipeline_stack.py**
``` py
        self.pipeline = PDKPipeline(
            self,
            "Pipeline",
            primary_synth_directory="cdk.out",
            repository_name=repo_name,
            default_branch_name=default_branch_name,
            publish_assets_in_parallel=False,
            docker_enabled_for_synth=True,
            synth=pipelines.ShellStep("Unused", commands=[]),
            synth_shell_step_partial_props={
                "install_commands": [
                    "npm install -g aws-cdk",
                    "pip install -r requirements-dev.txt",
                    "pip install -r requirements.txt",
                    "projen",
                ],
                "commands": ["projen build"],
            },
            cdk_command="cdk",
            branch_name_prefixes=PDKPipeline.ALL_BRANCHES,
        )
```

### Possible Solution

In this project, `cdk.out` and `cdk.json` are both in the root of the repository. The CodeBuild project should run cdk from the directory with `cdk.json`

### PDK version used

0.19.15

### What languages are you seeing this issue on?

Python

### Environment details (OS name and version, etc.)

MacOS 12.6.5

**Comment by jstrunk** [comment]
Please assign this to me

**Comment by agdimech** [comment]
@jstrunk - any update on this one?

**Comment by jstrunk** [comment]
I had a lot to do in June. I plan to work on it after July 20th.

**Comment by jstrunk** [comment]
I've isolated the issue. This would happen any time PDKPipeline is used without nx-monorepo. In the FeatureBranch CodeBuild job, I run `cdk deploy` because it's not run as part of a pipeline. That means `cdk deploy` needs to run in the directory with cdk.json instead of having the pipeline deploy the CloudFormation artifacts directly with CloudFormation.

In an nx-monorepo project, the `cdk.json` with be in a project subdirectory, but without nx-monorepo, it's in the project root.

I was trying to detect the location of `cdk.json` based on the `primarySynthDirectory` by removing the last part of the directory:
https://github.com/aws/aws-prototyping-sdk/blob/7f5f3fecfe501b4fb6d2686b65f92b4e15453e52/packages/pipeline/src/pdk-pipeline.ts#L344-L347

In the case of `cdk.json` in the project root, that generates a `"cd "` command in the buildspec before running `cdk deploy`:
https://github.com/aws/aws-prototyping-sdk/blob/7f5f3fecfe501b4fb6d2686b65f92b4e15453e52/packages/pipeline/src/pdk-pipeline.ts#L344-L347

@agdimech Which solution fits best here?

1. Shift up the `cdkSrcDir` prop to the developer so they can define it. I'd make it optional and only add a `cd ${props.cdkSrcDir}` command if it's defined. This is probably best if it's not safe to assume that cdk.json is not in the same directory as `cdk.out`.
2. Detect an empty value in the call to `FeatureBranches` in `pdk-pipeline.ts` and change it to undefined or `.`.
3. Detect an empty value in the buildspec definition at https://github.com/aws/aws-prototyping-sdk/blob/7f5f3fecfe501b4fb6d2686b65f92b4e15453e52/packages/pipeline/src/feature-branches.ts#L126 and remove the cd command or change it to `cd .`.

**Comment by jstrunk** [comment]
After further research, option 1 is my preference. The location of `cdk.out` is specified in `cdk.json` in the `output` attribute. I don't think there's a definitive way to determine the  location of `cdk.json` from `cdk.out`.

I will expose `cdkSrcDir` as an optional property of `PDKPipeline` and make the default be the same directory as `cdk.out` taking care to avoid running `"cd "`.
