### ISSUE TITLE
[BUG] Fails to build "myapi-typescript-infra"

### ISSUE THREAD

**Issue by sociengineer** [aws/aws-pdk#465]
### Describe the bug
Hello, I implemented type-safe-api in my pdk pipeline, but failed to build " myapi-typescript-infra".

Here are the error messages as follows:

src/api.ts(18,11): error TS2345: Argument of type 'import("/codebuild/output/src887991877/src/packages/api/infrastructure/typescript/node_modules/constructs/lib/construct").Construct' is not assignable to parameter of type 'import("/codebuild/output/src887991877/src/node_modules/constructs/lib/construct").Construct'. 

Types of property 'node' are incompatible. 

Type 'import("/codebuild/output/src887991877/src/packages/api/infrastructure/typescript/node_modules/constructs/lib/construct").Node' is not assignable to type 'import("/codebuild/output/src887991877/src/node_modules/constructs/lib/construct").Node'. 

Types have separate declarations of a private property 'host'. 

👾 Task "build » compile" failed when executing "tsc --build" (cwd: /codebuild/output/src887991877/src/packages/api/infrastructure/typescript) 
·[1Gerror Command failed with exit code 1. 
·[1Ginfo Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. 

Warning: run-commands command "yarn projen build" exited with non-zero status code 

> NX Running target build for 8 projects failed 

Tasks not run because their dependencies failed or --nx-bail=true: 
- infra:build 

Failed tasks: 
- myapi-python-runtime:build 
- myapi-typescript-infra:build 

[Container] 2023/06/11 10:21:09 Command did not exit successfully npx nx run-many --target=build --all exit status 1 
[Container] 2023/06/11 10:21:09 Phase complete: BUILD State: FAILED 
[Container] 2023/06/11 10:21:09 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: npx nx run-many --target=build --all. Reason: exit status 1

### Expected Behavior
Succeed in building "myapi-typescript-infra".

### Current Behavior

Failed to build two tasks:
- myapi-python-runtime:build
- myapi-typescript-infra:build

### Reproduction Steps

Following steps in the developer guide on Type Safe API 
https://aws.github.io/aws-prototyping-sdk/developer_guides/type-safe-api/index.html

### PDK version used

0.19.18

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

MacOS Monterey 12.6.6

**Comment by mteichtahl** [comment]
Can you please share any errors you may be receiving along with you .projenrc ?Please note: My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal work schedule!Sent on the go - please excuse mistakes On 11 Jun 2023, at 7:47 pm, Wookjae Maeng ***@***.***> wrote:﻿
Describe the bug
Generated typescript infrastructure package "myapi-typescript-infra" is not loadable
Expected Behavior
import { Api } from "myapi-typescript-infra";
Above code has no problem
Current Behavior
"myapi-typescript-infra" is not loadable
Reproduction Steps
Following steps in the developer guide on Type Safe API
https://aws.github.io/aws-prototyping-sdk/developer_guides/type-safe-api/index.html
Possible Solution
No response
Additional Information/Context
No response
PDK version used
0.19.18
What languages are you seeing this issue on?
Typescript
Environment details (OS name and version, etc.)
MacOS Monterey 12.6.6

**Comment by sociengineer** [comment]
@mteichtahl Sure. I edited the title and comments.

**Comment by cogwirrel** [comment]
Hi Wookjae, thanks for raising this!

This looks like a mismatch between `constructs` versions in the different packages. I wonder if you added `TypeSafeApiProject` to an existing project which used an older version of `constructs` or `aws-cdk-lib` than the latest?

To address this, I think updating `aws-cdk-lib` and `constructs` would be the most straightforward approach. You can do this with `npm-check-updates` from the root of your project:

```bash
npx npm-check-updates -u --deep constructs
npx npm-check-updates -u --deep aws-cdk-lib
```

Afterwards, run `yarn` and hopefully you'll see only a single version of `constructs` and `aws-cdk-lib` in your `yarn.lock` file.

Another approach if you need to use an older version is to use `resolutions` to pin aws-cdk-lib/constructs at particular versions, for example in your `.projenrc.ts`:

```ts
monorepo.package.addPackageResolutions("**/constructs@<version>", "**/aws-cdk-lib@<version>");
```

Hope that helps, let me know if this solves it! :)

**Comment by sociengineer** [comment]
Hi Jack, thanks for your kind guidance.

I addressed the issues using npm-check-updates. but I got another fail in building by infra code.
In infra, I just added the example code in my application-stack.ts of pdk pipeline.

```
import { Stack, StackProps } from 'aws-cdk-lib';
import { Construct } from 'constructs';
import { Api } from "myapi-typescript-infra"; // <- generated typescript infrastructure package
import { Authorizers, Integrations } from "@aws-prototyping-sdk/type-safe-api";
import { NodejsFunction } from "aws-cdk-lib/aws-lambda-nodejs";
import { Cors } from "aws-cdk-lib/aws-apigateway";
import * as path from "path";


export class ApplicationStack extends Stack {
  constructor(scope: Construct, id: string, props?: StackProps) {
    super(scope, id, props);

    new Api(this, "MyApi", {
      defaultAuthorizer: Authorizers.iam(),
      corsOptions: {
        allowOrigins: Cors.ALL_ORIGINS,
        allowMethods: Cors.ALL_METHODS,
      },
      // Supply an integration for every operation
      integrations: {
        sayHello: {
          integration: Integrations.lambda(
            new NodejsFunction(this, "SayHelloLambda", {
              entry: path.resolve('../lambda', "say-hello.ts"),
            })
          ),
        },
      },
    });
  }
}
```

The error message is as follows:

```
> nx run infra:build

·[1Gyarn run v1.22.19
·[1G$ /codebuild/output/src191379366/src/node_modules/.bin/projen build
👾 build » compile | tsc --build
../api/runtime/typescript/lib/runtime.d.ts(23,19): error TS2304: Cannot find name 'RequestCredentials'.
../api/runtime/typescript/lib/runtime.d.ts(38,24): error TS2304: Cannot find name 'RequestCredentials'.
../api/runtime/typescript/lib/runtime.d.ts(51,61): error TS2304: Cannot find name 'RequestInit'.
../api/runtime/typescript/lib/runtime.d.ts(51,106): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(61,15): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(63,27): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(81,24): error TS2304: Cannot find name 'WindowOrWorkerGlobalScope'.
../api/runtime/typescript/lib/runtime.d.ts(94,19): error TS2304: Cannot find name 'RequestCredentials'.
../api/runtime/typescript/lib/runtime.d.ts(101,15): error TS2304: Cannot find name 'RequestInit'.
../api/runtime/typescript/lib/runtime.d.ts(104,11): error TS2304: Cannot find name 'RequestInit'.
../api/runtime/typescript/lib/runtime.d.ts(123,11): error TS2304: Cannot find name 'RequestInit'.
../api/runtime/typescript/lib/runtime.d.ts(128,11): error TS2304: Cannot find name 'RequestInit'.
../api/runtime/typescript/lib/runtime.d.ts(129,15): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(134,11): error TS2304: Cannot find name 'RequestInit'.
../api/runtime/typescript/lib/runtime.d.ts(136,16): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(140,46): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(141,46): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(144,10): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(151,10): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(153,22): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(157,10): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(158,22): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(162,10): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(163,22): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(164,22): error TS2304: Cannot find name 'Blob'.
../api/runtime/typescript/lib/runtime.d.ts(167,10): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/runtime.d.ts(168,22): error TS2304: Cannot find name 'Response'.
../api/runtime/typescript/lib/apis/DefaultApi.d.ts(23,69): error TS2304: Cannot find name 'RequestInit'.
../api/runtime/typescript/lib/apis/DefaultApi.d.ts(26,66): error TS2304: Cannot find name 'RequestInit'.
👾 Task "build » compile" failed when executing "tsc --build" (cwd: /codebuild/output/src191379366/src/packages/infra)
```

**Comment by cogwirrel** [comment]
Followed up offline - just adding a note here in case others experience this.

To address this you can add `skipLibCheck: true` to your infrastructure project's tsconfig, eg:

```
new AwsCdkTypeScriptApp({
  ...
  tsconfig: {
    compilerOptions: {
      lib: ["dom", "es2019"],
      skipLibCheck: true
    }
  }
});
```

The generated typescript runtime project types rely on the `dom` lib (since it types the built in `fetch` api), and so you might see this error if you have type checking on your dependencies without the `dom` lib in your project.
