### ISSUE TITLE
yarn build intermittently fails with ```NX   ENOTEMPTY: directory not empty,```

### ISSUE THREAD

**Issue by mteichtahl** [aws/aws-pdk#488]
### Describe the bug

```yarn build``` intermittently fails with a ```NX   ENOTEMPTY: directory not empty,``` error. 

### Expected Behavior

```yarn build``` successfully completes

### Current Behavior

```yarn build``` fails (sometimes)

```
> nx run infra:build

infra: 👾 build » post-compile » synth:silent | cdk synth -q
infra: Bundling asset pear-paas-admin/RouterFunction/Code/Stage...
infra:   ...dbe4f4a0ef03ce214f5eef6f060789f3e0cec4843417de87edc05a5/index.js  5.2mb ⚠️
infra: ⚡ Done in 177ms
infra: 👾 build » test | jest --passWithNoTests --updateSnapshot
infra: No tests found, exiting with code 0
infra: ----------|---------|----------|---------|---------|-------------------
infra: File      | % Stmts | % Branch | % Funcs | % Lines | Uncovered Line #s 
infra: ----------|---------|----------|---------|---------|-------------------
infra: All files |       0 |        0 |       0 |       0 |                   
infra: ----------|---------|----------|---------|---------|-------------------
infra: 👾 build » test » eslint | eslint --ext .ts,.tsx --fix --no-error-on-unmatched-pattern src test test build-tools

 ———————————————————————————————————————————————————————————————————————————————————

 >  NX   Successfully ran target build for 8 projects

   Nx read the output from the cache instead of running the command for 6 out of 8 tasks.


 >  NX   ENOTEMPTY: directory not empty, rmdir '/Volumes/workplace/prototyping/pear/PaaSAdmin/node_modules/.cache/nx/f424d8b9ce512c8a1bafe9bf7e8779a43c62a0a210a8786a2296eb52664d9cda/outputs/packages/infra/cdk.out/asset.bdb1a4863171a51697917c7677578b210481dc66f518451e6d4316cc7aec6c44'

   Pass --verbose to see the stacktrace.

👾 Task "build" failed when executing "yarn exec nx run-many --target=build --output-style=stream --nx-bail" (cwd: /Volumes/workplace/prototyping/pear/PaaSAdmin)
╭─teichtah@bcd074228b1a /Volumes/workplace/prototyping/pear/PaaSAdmin ‹main› 
```

### Reproduction Steps

this is intermittent and may be difficult to reproduce. Locally, this is reproducible with about 4 out of 10 build failing.

### PDK version used

0.19.29

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Darwin bcd074228b1a.ant.amazon.com 22.5.0 Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 arm64

**Comment by agdimech** [comment]
Can you please confirm the version of NX you are experiencing this with? i.e: `yarn nx --version`

**Comment by agdimech** [comment]
This seems to be an issue in NX and appears to be related to: https://github.com/nrwl/nx/issues/17277

I assume if you run `nx reset` and the re-build the issue resolves?

**Comment by agdimech** [comment]
Seems like this issue was introduced as part of this change: https://github.com/nrwl/nx/commit/d3272108c9b8ce56306f1e2556e2656cf4a22c26

Looking into the issue it seems to be localized to this block of code: https://github.com/nrwl/nx/blob/fb0f1f0ec8e66d067462b94e182152f3eb596376/packages/nx/src/native/cache/file_ops.rs#L10

**Comment by agdimech** [comment]
PR is pending merge in NX :)

https://github.com/nrwl/nx/pull/18207

**Comment by agdimech** [comment]
As a workaround, ensure you only have unique entries in your outputs contained in project.json.

For example, the following is an erroneous outputs as it contains duplicated `cdk.out`:

```
"outputs": [
        "{projectRoot}/dist",
        "{projectRoot}/lib",
        "{projectRoot}/build",
        "{projectRoot}/coverage",
        "{projectRoot}/test-reports",
        "{projectRoot}/target",
        "{projectRoot}/cdk.out",
        "{projectRoot}/LICENSE_THIRD_PARTY",
        "{projectRoot}/.jsii",
        "{projectRoot}/cdk.out"
      ],
```

The fix is to ensure only a single `cdk.out` exists.
