### ISSUE TITLE
[BUG] PDKPipeline Update Pipeline stage mutating and deleting consequent stages

### ISSUE THREAD

**Issue by em-xqm** [aws/aws-pdk#492]
### Describe the bug

On first deploy of PDKPipeline, there are 5 stages. 

source -> build -> update pipeline -> assets -> Dev

But  once it goes to update pipeline stage , it reruns from source stage and the 'assets' stage and 'Dev' stage disappear

### Expected Behavior

Update pipeline should not be mutating and deleting stages. 

### Current Behavior

Update pipeline deleting stages that shouldn't be. 

Logs in CodeBuild from the update pipeline stage: 

![image (2)](https://github.com/aws/aws-prototyping-sdk/assets/56704051/7b23d73a-705a-468a-87ac-e6acf58bfdcf)

### Reproduction Steps

Deploy a brand new project with PDKPipeline. Then link the CodeCommit repository and push to that repository to trigger pipeline to run for the first time. You should get update pipeline mutating the pipeline and destroying stages.

### PDK version used

0.18.15

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

aws/codebuild/standard:6.0

**Comment by agdimech** [comment]
We concluded that this was an issue with synth that was swallowing errors and continuing to deploy. This is not an issue with PDK and hence closing.
