### ISSUE TITLE
[BUG] (static-website): WAF creation custom resource returns WAFUnavailableEntityException

### ISSUE THREAD

**Issue by jessieweiyi** [aws/aws-pdk#508]
### Describe the bug

My PDK app includes PDK static-website construct and the static-website construct has the cidrAllowList configured. 

When I deployed the app to the us-east-1 region, the deployment failed for most of times (4 out of 5 times) because the WAF creation custom resource returns WAFUnavailableEntityException. 

Below is the CloudWatch log for the WAF custom resource lambda:

```
{
    "errorType": "WAFUnavailableEntityException",
    "errorMessage": "AWS WAF couldn't retrieve the resource that you requested. Retry your request.",
    "code": "WAFUnavailableEntityException",
    "message": "AWS WAF couldn't retrieve the resource that you requested. Retry your request.",
    "time": "2023-07-17T06:45:23.046Z",
    "requestId": "f2e343bb-86e3-441f-99b6-59a88fc139e4",
    "statusCode": 400,
    "retryable": false,
    "retryDelay": 16.044677277845267,
    "stack": [
        "WAFUnavailableEntityException: AWS WAF couldn't retrieve the resource that you requested. Retry your request.",
        "    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:61:27)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:106:20)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:78:10)",
        "    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:686:14)",
        "    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)",
        "    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)",
        "    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)",
        "    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:688:12)",
        "    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:116:18)"
    ]
}
```

This might be a timing issue where the IPSet records are not propagated before the WebACL record is created according to the (CreateWebACL API doc)[https://docs.aws.amazon.com/waf/latest/APIReference/API_CreateWebACL.html], 

> AWS WAF couldn’t retrieve a resource that you specified for this operation. If you've just created a resource that you're using in this operation, you might just need to wait a few minutes. It can take from a few seconds to a number of minutes for changes to propagate. Verify the resources that you are specifying in your request parameters and then retry the operation.

### Expected Behavior

The PDK app should be deployed successfully.  

### Current Behavior

The PDK app deployment failed due to unsuccessful WAF creation 

### Reproduction Steps

1. Create a PDK app including static website construct
2. Provide webAclProps:
```
webAclProps: {
        cidrAllowList: {
          cidrType: "IPV4",
          cidrRanges: ["0.0.0.0/1","128.0.0.0/1"]
        },
      },
```
3. Deploy the app to us-east-1 region

### Possible Solution

Include a retry mechanism in the createWebACL function if it is due to WAFUnavailableEntityException error.

### PDK version used

0.19.2

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

MacOS Ventura 13.3.1

**Comment by JeremyJonas** [comment]
If it is a race condition, should check to make sure there is proper dependency on the custom waf resource and the resource (website) that depends on this.

**Comment by cogwirrel** [comment]
Closed by above PR :)
