### ISSUE TITLE
[BUG] TypeSafeApi - resource-based policies exceed hard limit of 20K

### ISSUE THREAD

**Issue by mteichtahl** [aws/aws-pdk#549]
### Describe the bug

For an API with a large surface area (>50 operations), TypeSafeApi generates a lambda resource policy that exceeds the AWS hard limit (according to ```https://docs.aws.amazon.com/lambda/latest/dg/access-control-resource-based.html```) which causes deployment failures.

### Expected Behavior

The generated resource policy should not exceed 20Kb and allow effectively unlimited operations/handlers

### Current Behavior

The implementation begin used is based on ```handlerRouter```

```
export const handler = handlerRouter({
  interceptors: [corsInterceptor, tryCatchInterceptor, identityInterceptor],
  handlers: { ... } // 51 handlers
});
```

on deployment, cloudFormation throws
```
Resource handler returned message: "The final policy size (20778) is bigger than the limit (20480). (Service: Lambda, Status Code: 400, Request ID: 3fbf0839-1916-4983-90c0-b53a7ddd2ce0)" (RequestToken: 44ce75cc-79b2-9de4-5d28-0ff14066ab80, HandlerErrorCode: InvalidRequest)
```

### Reproduction Steps

```
export const handler = handlerRouter({
  interceptors: [corsInterceptor, tryCatchInterceptor, identityInterceptor],
  handlers: { ... } // 51 handlers
});
```

### Possible Solution

Optimisation of ```https://github.com/aws/aws-prototyping-sdk/blob/1fcf948a2f0f87ee28f69e231f79a3e8ce6b6ea6/packages/type-safe-api/src/construct/integrations/lambda.ts#L46C4-L57C14``` when ```handlerRouter``` is being used

### PDK version used

0.19.47

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Darwin 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64

**Comment by cogwirrel** [comment]
Thanks for reporting this!

It would probably make sense for the construct to track when the same lambda is used for multiple integrations and to relax the policy in this case.

In the mean time you can work around this issue by creating your own lambda integration which overrides the `grant` method to do nothing:

```ts
import { LambdaIntegration } from "@aws-prototyping-sdk/type-safe-api";
import { IFunction } from "aws-cdk-lib/aws-lambda";

export class LambdaRouterIntegration extends LambdaIntegration {
  public static of(fn: IFunction) {
    return new LambdaRouterIntegration(fn);
  }

  public grant() {
    // Do nothing
  }
}
```

Then replace your usage of `Integrations.lambda(myRouterFunction)` with `LambdaRouterIntegration.of(myRouterFunction)`.

And then finally add a single permission to your lambda function, eg:

```ts
import { Stack } from "aws-cdk-lib";
import { CfnPermission } from "aws-cdk-lib/aws-lambda";

new CfnPermission(this, `LambdaRouterPermission`, {
  action: "lambda:InvokeFunction",
  principal: "apigateway.amazonaws.com",
  functionName: myRouterFunction.functionArn,
  sourceArn: Stack.of(this).formatArn({
    service: "execute-api",
    resource: api.restApiId,
    resourceName: '*',
  }),
});
```
