### ISSUE TITLE
[BUG] Refactor syncpack to >= 9

### ISSUE THREAD

**Issue by agdimech** [aws/aws-pdk#553]
### Describe the bug

Upgrade syncpack config to incorporate https://github.com/JamieMason/syncpack/releases/tag/9.0.0

### Expected Behavior

https://github.com/JamieMason/syncpack/releases/tag/9.0.0

### Current Behavior

https://github.com/JamieMason/syncpack/releases/tag/9.0.0

### Reproduction Steps

https://github.com/JamieMason/syncpack/releases/tag/9.0.0

### PDK version used

latest

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

all

**Comment by JamieMason** [comment]
These changes will hopefully help get you started: https://github.com/JamieMason/aws-pdk/commit/561b6579de1002f8029fd36e72b9412e9cce8eab.

Re: your `upgrade-deps` command which runs `syncpack fix-mismatches`, I'm not sure if syncpack is quite set up right just yet – there is a new [Getting Started](https://jamiemason.github.io/syncpack/guide/getting-started) guide which will hopefully help you configure syncpack to better suit your project.

Hope this helps, thanks.

**Comment by agdimech** [comment]
> These changes will hopefully help get you started: [JamieMason@561b657](https://github.com/JamieMason/aws-pdk/commit/561b6579de1002f8029fd36e72b9412e9cce8eab).
> 
> Re: your `upgrade-deps` command which runs `syncpack fix-mismatches`, I'm not sure if syncpack is quite set up right just yet – there is a new [Getting Started](https://jamiemason.github.io/syncpack/guide/getting-started) guide which will hopefully help you configure syncpack to better suit your project.
> 
> Hope this helps, thanks.

Fantastic - thank you so much for your help :D 🕺

**Comment by cogwirrel** [comment]
Resolved in https://github.com/aws/aws-pdk/pull/691
