### ISSUE TITLE
[FEATURE] add `bun` as a NodePackageManager

### ISSUE THREAD

**Issue by sperka** [aws/aws-pdk#576]
### Describe the feature

Use [bun](https://bun.sh/docs) for package management and other tasks (e.g.: `bunx` instead of `npx` or `pnpm dlx`).

### Use Case

Adds better performance for dev tasks.

### Proposed Solution

`NodePackageUtils.command`, etc.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PDK version used

latest

### What languages will this feature affect?

Typescript

### Environment details (OS name and version, etc.)

MacOS

**Comment by agdimech** [comment]
Hi mate,

This shouldn't be too hard to do however would require some PR's to be written within Projen to add a new `NodePackageManager`.

As an aside, bun is still relatively new and does have some limitations in terms of being a full-fledged package manager. The biggest gap I can see at the moment is its lack of configurability with regard to hoisting packages along with the fact it does not have a built in packager (equivalent to npm pack). From a JSII perspective, bun would be unusable as all of the bundleddeps would be excluded from the built dist.

Will keep this open as a 'nice to have' and depending on community interest it can be re-prioritized.
