### ISSUE TITLE
monorepo devDep on "@aws/pdk@^0" prevents consumer from defining version

### ISSUE THREAD

**Issue by JeremyJonas** [aws/aws-pdk#586]
By having devDep on `@aws/pdk@^0` pinned to `^0` it overrides any consumer devDep on pdk set in options. Which is preventing pulling the latest in consuming repo. 

https://github.com/aws/aws-pdk/blob/1a542c19973e3b999be496636051fe5e9e586323/packages/monorepo/src/projects/typescript/monorepo-ts.ts#L277C31-L277C44

## Work Around
Have to override the devDep after monorepo constructor
```typescript
super(...)

this.addDevDeps("@aws/pdk@^0.22.9");
```

## Proposal
We should be checking to see if "@aws/pdk" is already added to the deps, and only add it if missing

**Comment by agdimech** [comment]
Resolved in https://github.com/aws/aws-pdk/pull/602
