### ISSUE TITLE
[BUG] allow overriding @types/node version

### ISSUE THREAD

**Issue by janeklb** [aws/aws-pdk#616]
### Describe the bug

The docs recommend using node 18 (https://aws.github.io/aws-pdk/getting_started/index.html#node-runtime); however, if I add `@types/node@^18.18.2` to my monorepo `devDeps` it gets overridden back to `@types/node@^16`

### Expected Behavior

If `@types/node` is added to a monorepo's `deps`/`devDeps`, it should be reflected in the synthesised files.

### Current Behavior

If `@types/node` is added to a monorepo's `deps`/`devDeps`, it is not reflected in the synthesised files.

### Reproduction Steps

Create a monorepo project with `devDeps: ["@types/node@^18.18.7"]`, then check your lock file, package.json etc. to see you're still using `"@types/node@^16"`.

### PDK version used

0.22.20

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

MacOS Ventura 13.5

**Comment by agdimech** [comment]
Hi - you can specifiy `minNodeVersion` as a constructor arg.
