### ISSUE TITLE
[BUG] (cannot create new monorepo-py)

### ISSUE THREAD

**Issue by janrichter-fsq** [aws/aws-pdk#643]
### Describe the bug

When creating a new monorepo in Python via command `pdk new monorepo-py` the installation fails.

### Expected Behavior

Installation finishes successfully with new Python monorepo created.

### Current Behavior

When installing Poetry dependencies, the process fails with:

```
Resolving dependencies... (1.0s)

Because pdk-python1 depends on @aws/pdk (*) which doesn't match any versions, version solving failed.
/Users/falnyr/projects/pdk-python1/node_modules/projen/lib/task-runtime.js:155
                    throw new Error(`Task "${this.fullname}" failed when executing "${command}" (cwd: ${(0, path_1.resolve)(cwd ?? this.workdir)})`);
                    ^

Error: Task "install" failed when executing "poetry update" (cwd: /Users/falnyr/projects/pdk-python1)
```

### Reproduction Steps

Run `pdk new monorepo-py` in an empty folder.

### Possible Solution

Current workaround is to remove `dev_deps=["@aws/pdk"]` dev dependency from `.projenrc.py` and run `pdk` again.

### Additional Information/Context

Poetry (version 1.7.0)
Python 3.11.5

### PDK version used

0.22.13

### What languages are you seeing this issue on?

Python

### Environment details (OS name and version, etc.)

MacOS Sonoma 14.1.1

**Comment by cogwirrel** [comment]
Related projen bug: https://github.com/projen/projen/issues/2475

Until the above is addressed I think we could work around it by having the `MonorepoPyProject` remove any dep called `@aws/pdk`
