### ISSUE TITLE
[BUG] aenum based unit tests seem broken

### ISSUE THREAD

**Issue by dbryson** [aws/aws-pdk#655]
### Describe the bug

When following the typesafeapi document, I got to the step where one needs to run tests on the infrastructure.  And it appears the aenum package has failing unit tests. 

### Expected Behavior

I expected the infrastructure to build and run tests with a success code.

### Current Behavior

 Here is the errors I get:

`============================================================ short test summary info ============================================================
FAILED cdk.out/asset.da8c7c102fcd20cecb3593d5a2b396a3ed3e536a31ccf35c312daaea6fd21e81/aenum/test_v3.py::TestEnumV3::test_class_nested_enum_and_pickle_protocol_four - NameError: name 'test_pickle_dump_load' is not defined
FAILED cdk.out/asset.da8c7c102fcd20cecb3593d5a2b396a3ed3e536a31ccf35c312daaea6fd21e81/aenum/test_v3.py::TestEnumV3::test_pickle_enum_function_with_qualname - NameError: name 'test_pickle_dump_load' is not defined
FAILED cdk.out/asset.da8c7c102fcd20cecb3593d5a2b396a3ed3e536a31ccf35c312daaea6fd21e81/aenum/test_v3.py::TestEnumV3::test_subclasses_with_getnewargs_ex - NameError: name 'test_pickle_dump_load' is not defined
FAILED cdk.out/asset.da8c7c102fcd20cecb3593d5a2b396a3ed3e536a31ccf35c312daaea6fd21e81/aenum/test_v3.py::TestStackoverflowAnswersV3::test_arduino_headers - NameError: name 'tempdir' is not defined
FAILED cdk.out/asset.da8c7c102fcd20cecb3593d5a2b396a3ed3e536a31ccf35c312daaea6fd21e81/aenum/test_v3.py::TestExtendEnumV3::test_extend_enum_shadow_property_stdlib - AttributeError: <enum 'Color'> has no attribute 'value'. Did you mean: 'blue'?
`

### Reproduction Steps

I followed the type_safe_api guidelines, and after adding the 'SayGoodbye' api call I ran `pdk build` to get the above error.

### PDK version used

0.22.41

### What languages are you seeing this issue on?

Python

### Environment details (OS name and version, etc.)

macos, ventura 13.6

**Comment by cogwirrel** [comment]
Hey, thanks for raising this!

It looks like pytest is looking in `cdk.out` which it shouldn't do - we need to update the test tasks to point at just the test directory.

I'll send a PR to fix this shortly!

**Comment by cogwirrel** [comment]
Note as a workaround you can adjust your `.projenrc.py` as follows:

```python
infra = InfrastructurePyProject(
    parent=monorepo,
    outdir="packages/infra",
    name="infra",
    type_safe_api=api,
)
infra.test_task.reset()
infra.test_task.exec("poetry run pytest tests/")
```

**Comment by dbryson** [comment]
That works,  I'm pretty new to poetry and projen, so I wasn't even thinking that pytest needed args.  Thanks!

**Comment by cogwirrel** [comment]
No problem! :) I'm going to keep this open till the PR is merged though as ideally everything should just work out of the box! :)
