### ISSUE TITLE
[BUG] Missing AWS Icons in Diagrams

### ISSUE THREAD

**Issue by chris-bateman** [aws/aws-pdk#679]
### Describe the bug

The Diagrams generated by the CdkGraphDiagramPlugin are missing the AWS icons.

### Expected Behavior

AWS icons appear in diagram.

### Current Behavior

Icons are missing in diagram.
![image](https://github.com/aws/aws-pdk/assets/12206103/e83c90f2-0481-43d3-b45e-f308012723b2)
![image](https://github.com/aws/aws-pdk/assets/12206103/3aab9730-3278-43f0-a1b3-984a8a6f96e8)

### Reproduction Steps

```
const graph = new CdkGraph(app,
  {
    plugins: [
      new cdk_graph_plugin_diagram.CdkGraphDiagramPlugin(
      )
    ],
  }
  )

  app.synth();

graph.report();
```
Run cdk diff
Diagrams appear in cdk.out dir but are missing images.

### Additional Information/Context

Do these images need to be preloaded into the project?

### PDK version used

v0.22.49

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Windows 11, Node 18.19.0, CDK 2.121.1

**Comment by chris-bateman** [comment]
Adding that the images are in Node Modules - 
![image](https://github.com/aws/aws-pdk/assets/12206103/6126880d-2c21-4cfc-9521-9bbfdc249114)

**Comment by chris-bateman** [comment]
Interesting it works on Ubuntu WSL perfectly.  Might clear my setup and just try fresh in Windows to see what happens.

**Comment by agdimech** [comment]
HI Chris - glad you managed to get it working. Were you trying to run PDK via WSL initially or directly on windows?

**Comment by chris-bateman** [comment]
> HI Chris - glad you managed to get it working. Were you trying to run PDK via WSL initially or directly on windows?

Directly on Windows first which failed.  Then I moved to WSL as a troubleshooting step and it worked instantly.

**Comment by agdimech** [comment]
OK great. We do not support windows native at the moment and definitely recommend WSL.

I will close this as we are tracking onboarding for windows/WSL in a seperate ticket: #664 . Please feel free to re-open if you feel this was closed in error or your issue is still unresolved.

Also - welcome to PDK land :)

**Comment by mteichtahl** [comment]
Have we considered a case issue ?Please note: My working hours may not be your working hours. Please do not feel obligated to reply outside of your normal work schedule!Sent on the go - please excuse mistakes On 16 Jan 2024, at 10:02 am, Chris Bateman ***@***.***> wrote:﻿

HI Chris - glad you managed to get it working. Were you trying to run PDK via WSL initially or directly on windows?

Directly on Windows first which failed.  Then I moved to WSL as a troubleshooting step and it worked instantly.
