### ISSUE TITLE
[BUG] Pypi packages no longer publishing(project out of space)

### ISSUE THREAD

**Issue by dbryson** [aws/aws-pdk#689]
### Describe the bug

The latest version of aws_pdk on pypi is 0.22.46([pypi](https://pypi.org/project/aws-pdk/#history).  I checked the build action and it looks like it has been failing silently:
https://github.com/aws/aws-pdk/actions/runs/7622167486/job/20759894009#step:6:168

`<h1>400 Project size too large. Limit for project 'aws-pdk' total   `

### Expected Behavior

Builds should be published on pypi.

### Current Behavior

`
INFO     Response from https://upload.pypi.org/legacy/:                         
         400 Project size too large. Limit for project 'aws-pdk' total size is  
         10 GB. See https://pypi.org/help/#project-size-limit                   
INFO     <html>                                                                 
          <head>                                                                
           <title>400 Project size too large. Limit for project 'aws-pdk' total 
         size is 10 GB. See https://pypi.org/help/#project-size-limit</title>   
          </head>                                                               
          <body>                                                                
           <h1>400 Project size too large. Limit for project 'aws-pdk' total    
         size is 10 GB. See https://pypi.org/help/#project-size-limit</h1>      
           The server could not comply with the request since it is either      
         malformed or otherwise incorrect.<br/><br/>                            
         Project size too large. Limit for project &#x27;aws-pdk&#x27; total    
         size is 10 GB. See https://pypi.org/help/#project-size-limit           
                                                                                
                                                                                
          </body>                                                               
         </html>                                                                
ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
         Project size too large. Limit for project 'aws-pdk' total size is 10   
         GB. See https://pypi.org/help/#project-size-limit      
`

### Reproduction Steps

Start a new release build, and wait for Publish to PyPi to fail

### PDK version used

0.22.52

### Environment details (OS name and version, etc.)

github

**Comment by agdimech** [comment]
Ahh good catch - there seems to be a bug in the release workflow due to some legacy code that was not cleaned up. I will post a PR shortly to address this.

I have also raised an issue with PYPI to try and get the Project Size increased to 50Gb. https://github.com/pypi/support/issues/3558

**Comment by agdimech** [comment]
Still waiting for the PyPi team to respond. In the meantime I am going to try and see if I can optimize the bundling of the PDK to try and reduce the size.

**Comment by agdimech** [comment]
Apologies @dbryson - Still no word on the Github ticket. Based on averages, it takes ~1 month to resolve these types of issues...

**Comment by agdimech** [comment]
I managed to push a new release here: https://pypi.org/project/aws-pdk/0.23.7/

The issue is still not resolved however, I just managed to reduce the bundle size of PDK with some optimizations :)

Hopefully this unblocks you for now.

**Comment by agdimech** [comment]
Limit has been bumped to 20GB :)
