### ISSUE TITLE
[BUG] (cdk-graph-plugin-threat-composer) Generated architecture image too large for threat composer

### ISSUE THREAD

**Issue by cogwirrel** [aws/aws-pdk#721]
### Describe the bug

After adding some infrastructure, the embedded png image can be too large to import to threat composer.

### Expected Behavior

Able to import a generated threat model into threat composer.

### Current Behavior

![Screenshot 2024-03-14 at 9 23 51 am](https://github.com/aws/aws-pdk/assets/1848603/a3ce823c-9d56-4a5c-84ec-a905ab718751)

### Reproduction Steps

Add a few components, import the generated `threat-model.tc.json` file into threat composer.

### Possible Solution

Add support for svg images in threat composer as they will likely be much smaller. Consider also increasing the size limit.

### PDK version used

0.23.13

### What languages are you seeing this issue on?

Typescript, Java, Python

### Environment details (OS name and version, etc.)

OSX

**Comment by agdimech** [comment]
Is this a bug in PDK or Threat composer?

**Comment by cogwirrel** [comment]
Kind of both, I've raised one for threat composer here: https://github.com/awslabs/threat-composer/issues/100

I think we should keep this open so we remember to switch to svg output.
