### ISSUE TITLE
[FEATURE] replace deprecated @aws-sdk packages

### ISSUE THREAD

**Issue by sperka** [aws/aws-pdk#763]
### Describe the feature

There are a few `@aws-sdk/xxx` packages deprecated in favor of `@smithy/xxx` packages.

* [@aws-sdk/protocol-http](https://www.npmjs.com/package/@aws-sdk/protocol-http)
* [@aws-sdk/querystring-parser](https://www.npmjs.com/package/@aws-sdk/querystring-parser)
* [@aws-sdk/signature-v4](https://www.npmjs.com/package/@aws-sdk/signature-v4)

### Use Case

Sometimes you just need to use these `@aws-sdk/xxx` packages.

### Proposed Solution

Replace `@aws-sdk/xxx` to `@smithy/xxx`

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PDK version used

0.23.31

### What languages will this feature affect?

Typescript

### Environment details (OS name and version, etc.)

MacOS 14.4.1

**Comment by jsamuel1** [comment]
This should be prioritized.  The old SDK packages are getting a bit long in the tooth.
@martenpayne

**Comment by jsamuel1** [comment]
Has anything been done here?
