### ISSUE TITLE
[BUG] (type-safe-api) dev container out of date with respect to code

### ISSUE THREAD

**Issue by memorsolutions** [aws/aws-pdk#839]
### Describe the bug

Commit 345eb6f2a415a9394e65f79f382a1d8ad1fe8b04 introduced changes that require node v18.20 or higher as well as a dependency on rsync. The Docker image for the devcontainer is sill using node v18.19.0 and does not install rsync. This results in failed builds using the devcontainer.

### Expected Behavior

The build should succeed when built from the devcontainer.

### Current Behavior

The build fails.

### Reproduction Steps

run `pnpm build` from within the devcontainer.

### Possible Solution

Modify Dockerfile to install rssync and updated NODE_VERSION to v18.20.0 or higher.

### PDK version used

0.23.55

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Ubuntu 22.04

**Comment by memorsolutions** [comment]
@cogwirrel , given that #843 has been integrated. Any info on when to expect the image in ECR will get updated?

**Comment by cogwirrel** [comment]
Hey @memorsolutions sorry I missed this! I've just published the updated image so it should be available now :)
