### ISSUE TITLE
[BUG] type-safe-api.parse-openapi-spec command not found

### ISSUE THREAD

**Issue by davidpintotrusst** [aws/aws-pdk#840]
### Describe the bug

During the build of a typesafe api project when running the following command:

npx --yes -p @aws/pdk@$AWS_PDK_VERSION type-safe-api.parse-openapi-spec

The following error is output:

sh: type-safe-api.parse-openapi-spec: command not found

### Expected Behavior

It was expected that the spec is read

### Current Behavior

sh: type-safe-api.parse-openapi-spec: command not found

Task "build » compile » generate" failed when executing "npx --yes -p @aws/pdk@$AWS_PDK_VERSION type-safe-api.parse-openapi-spec

### Reproduction Steps

Running the build with typesafeapi using pdk version 0.23.55

### PDK version used

0.23.55

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

macOSX Ventura 13.6.9 npm 9.8.1 node 18.18.2

**Comment by cogwirrel** [comment]
Hi! That script has now been moved to a subcommand of the `type-safe-api` command (see here). Please can you try re-synthesising your project files (eg `npx projen`)? That should update your projects to point to the new script.

**Comment by cogwirrel** [comment]
Closing this as re-synthesizing will adjust the command that's run from `type-safe-api.parse-openapi-spec` to `type-safe-api parse-openapi-spec`. Feel free to comment and reopen if you're still having issues! :)
