### ISSUE TITLE
[FEATURE] Predetermined node positions

### ISSUE THREAD

**Issue by martinjlowm** [aws/aws-pdk#853]
### Describe the feature

DOT supports the pos attribute (https://github.com/ts-graphviz/ts-graphviz/blob/af5a52474ca13065385b775d52d410b448d8b3a4/packages/common/src/attribute.ts#L2208-L2227) to define the position of a node. The `@aws/pdk/cdk-graph` (and the diagram plugin) should accept and account for a map of node ids and their positions (`Map<NodeId, Pos>`) to specify the location of specific nodes. This could apply for the DrawIO and the Graphviz provider.

### Use Case

While the current state of exported architecture diagrams is neat as a baseline, it often requires architects to make it easier to interpret by a humans. Manually editing the diagram to a certain layout is tedious and redundant if it can be automated by providing node positions given by ids, so it remains consistent between new diagram revisions.

### Proposed Solution

1. Extend the diagram config with

```typescript
export interface IDiagramConfigBase {
  /**
   * The output format(s) to generated.
   * @default `DiagramFormat.PNG` - which will through extension also generate `DiagramFormat.SVG` and `DiagramFormat.DOT`
   */
  readonly format?: DiagramFormat | DiagramFormat[];

  /** Graph {@link IGraphFilterPlan Filter Plan}  used to generate a unique diagram */
  readonly filterPlan?: IGraphFilterPlan;

  /** Config for graph theme */
  readonly theme?: GraphThemeConfigProp;

  /** Config for predetermined node positions */
  readonly positions?: Map<string, Point>;

}
```

2. extend https://github.com/aws/aws-pdk/blob/mainline/packages/cdk-graph/src/core/graph.ts#L1109 with a position field
3. and use those positions in https://github.com/aws/aws-pdk/blob/mainline/packages/cdk-graph-plugin-diagram/src/internal/graphviz/entities/nodes.ts#L66 to set the `pos` attribute in the emitted DOT output.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### PDK version used

0.23.37

### What languages will this feature affect?

Typescript

### Environment details (OS name and version, etc.)

MacOS Sequoia 15.0.1

**Comment by cogwirrel** [comment]
Hi Martin, this sounds like a very useful feature! :) More than happy to review a PR if you have the bandwidth to look into contributing this! Cheers!
