### ISSUE TITLE
[BUG] (type-safe-api) api.model is not a projen.Project anymore

### ISSUE THREAD

**Issue by v41e** [aws/aws-pdk#876]
### Describe the bug

In `projenrc.ts`, if I want to manipulate an array of projects and want to include resulting `api.model` I can't.

### Expected Behavior

Keep `api.model` a `projen.Project`

### Current Behavior

I got following error in my editor

```
Argument of type 'ModelProject' is not assignable to parameter of type 'Project'.
  Type 'ModelProject' is missing the following properties from type 'Project': name, gitignore, gitattributes, tasks, and 35 more.ts(2345)
```

### Reproduction Steps

1. Follow getting started
2. Append following code
3. Observe error on line `api.model,`

```ts
const projects: projen.Project[] = []

projects.push(
  api.model,
  ...[
    api.runtime.java,
    api.runtime.python,
    api.runtime.typescript,
    api.infrastructure.java,
    api.infrastructure.python,
    api.infrastructure.typescript,
    api.handlers.java,
    api.handlers.python,
    api.handlers.typescript,
    api.documentation.htmlRedoc,
    api.documentation.markdown,
    api.documentation.plantuml,
  ].flatMap((project) => (project == undefined ? [] : [project])),
)
```

### Possible Solution

Instead of extending `ModelProjectDetails` it should be implemented and keep extending `projen.Project`

### PDK version used

v0.25.0

### Environment details (OS name and version, etc.)

macOS 15.0.1, apple m1 pro, node 20.18.0, pnpm 8.15.9

**Comment by v41e** [comment]
or at least underlying openapi or smithy project should be available

**Comment by cogwirrel** [comment]
Hey @valebedu! 

The breaking change in 0.25.x means that model projects are now more consistent with other projects (runtime, infra etc). You can access the project instances via `api.model.smithy` or `api.model.openapi`.

Also for a list of all the projects in the api you can use `api.all.projects` instead of creating it yourself :)

Hope that helps!

Cheers,
Jack

**Comment by v41e** [comment]
i'm so sorry i didn't see that openapi and smithy projects were already available, thanks a lot for your quick response :)

**Comment by cogwirrel** [comment]
No problem! :)
