### ISSUE TITLE
[BUG] Typescript API handlers can't use compiled dependencies

### ISSUE THREAD

**Issue by jstrunk** [aws/aws-pdk#879]
### Describe the bug

I wanted to add sharp as a dependency. esbuild does not package it correctly, so it is missing library files.

### Expected Behavior

The sharp dependency gets packaged outside of the single js file.

### Current Behavior

On Lambda function init, it throws the following error when importing sharp:

```
{
    "errorType": "Error",
    "errorMessage": "Could not load the \"sharp\" module using the linux-arm64 runtime\nPossible solutions:\n- Ensure optional dependencies can be installed:\n    npm install --include=optional sharp\n- Ensure your package manager supports multi-platform installation:\n    See https://sharp.pixelplumbing.com/install#cross-platform\n- Add platform-specific dependencies:\n    npm install --os=linux --cpu=arm64 sharp\n- Consult the installation documentation:\n    See https://sharp.pixelplumbing.com/install",
    "stack": [
        "Error: Could not load the \"sharp\" module using the linux-arm64 runtime",
        "Possible solutions:",
        "- Ensure optional dependencies can be installed:",
        "    npm install --include=optional sharp",
        "- Ensure your package manager supports multi-platform installation:",
        "    See https://sharp.pixelplumbing.com/install#cross-platform",
        "- Add platform-specific dependencies:",
        "    npm install --os=linux --cpu=arm64 sharp",
        "- Consult the installation documentation:",
        "    See https://sharp.pixelplumbing.com/install",
        "    at ../../../../node_modules/.pnpm/sharp@0.33.5/node_modules/sharp/lib/sharp.js (/var/task/index.js:48448:13)",
        "    at __require (/var/task/index.js:12:50)",
        "    at ../../../../node_modules/.pnpm/sharp@0.33.5/node_modules/sharp/lib/constructor.js (/var/task/index.js:48460:5)",
        "    at __require (/var/task/index.js:12:50)",
        "    at ../../../../node_modules/.pnpm/sharp@0.33.5/node_modules/sharp/lib/index.js (/var/task/index.js:52643:17)",
        "    at __require (/var/task/index.js:12:50)",
        "    at Object.<anonymous> (/var/task/index.js:54030:28)",
        "    at Module._compile (node:internal/modules/cjs/loader:1364:14)",
        "    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)",
        "    at Module.load (node:internal/modules/cjs/loader:1203:32)"
    ]
}
```

### Reproduction Steps

Create a typesafe api with a typescript handler with sharp as a dependency.

### Possible Solution

We could add an option to designate certain dependencies as "external" with esbuild and use that in https://github.com/aws/aws-pdk/blob/mainline/packages/type-safe-api/src/project/codegen/handlers/generated-typescript-handlers-base-project.ts#L110-L118 . https://sharp.pixelplumbing.com/install#esbuild

### PDK version used

0.23.64

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

mac os 14.7 intel

**Comment by jstrunk** [comment]
That possible solution is only partial. It also needs a way to add the external package to the lambda package.

**Comment by jstrunk** [comment]
To add the external packages to node_modules, we could add a barebones package.json with just name, version, and maybe main to `dist/lambda` and run `npm install --os=linux --cpu=$ARCH $EXTERNAL_PACKAGES`.

**Comment by cogwirrel** [comment]
Hey Jeff!

Thanks for raising this! There's a [short section in the docs about this sort of use case](https://aws.github.io/aws-pdk/developer_guides/type-safe-api/lambda_handlers.html#lambda-architectures), though I think it could definitely be elaborated on!

The current recommendation is to customise the `package` task, though for more complex projects with compiled dependencies or other non-bundleable dependencies it may be easier to omit the `@handler` trait all together and bundle/wire things up manually, using eg [`NodejsFunction`](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_lambda_nodejs-readme.html).

If you have the bandwidth I'm happy to review a PR that makes it easier to work with these sorts of dependencies in the handlers package though! :)

Cheers,
Jack

**Comment by jstrunk** [comment]
Thanks for the feedback. I'm testing out a custom package task to see if it
would be reasonable to generalize.

**Comment by jstrunk** [comment]
My custom package task call to `npm install --cpu=arm64 --os=linux --libc=glibc sharp` didn't get the binaries. I'm going with an alternative for now.

Thank you for pointing out the documentation.

**Comment by cogwirrel** [comment]
Cool no worries - I'll close this but if you ever find a nice way to generify I'm still happy for a PR 😄
