### ISSUE TITLE
[BUG] constructs version is locked in the pdk peerDependencies

### ISSUE THREAD

**Issue by varma415** [aws/aws-pdk#886]
### Describe the bug

Since constructs version is locked in the pdk peerDependencies, this is causing version conflicts in our monorepo.

PDK should allow users to choose constructs version of their choice based on the semver convention like ~, ^ etc.,

### Expected Behavior

  "peerDependencies": {
    "@aws-cdk/aws-cognito-identitypool-alpha": "^2.163.1-alpha.0",
    "aws-cdk-lib": "^2.163.1",
    "cdk-nag": "2.31.0",
    "constructs": "^10.4.2",
    "projen": "^0.82.8"
  },

### Current Behavior

  "peerDependencies": {
    "@aws-cdk/aws-cognito-identitypool-alpha": "^2.163.1-alpha.0",
    "aws-cdk-lib": "^2.163.1",
    "cdk-nag": "2.31.0",
    "constructs": "10.4.2",
    "projen": "^0.82.8"
  },

### Reproduction Steps

Open node_modules/@aws/pdk/package.json

### PDK version used

0.25.8

### What languages are you seeing this issue on?

Typescript

### Environment details (OS name and version, etc.)

Amazon Linux 2

**Comment by koduruprasanth** [comment]
This is similar to #830. 

I observed that the fix implemented  in #830 primarily addresses concerns with `aws-cdk-lib`, making it simpler to update its version. However, it seems that the version of `constructs` is still locked at `10.4.2`, which may lead to similar limitations as highlighted in #830.
